IF OBJECT_ID('ConfirmMgr.USER_MASTER') IS NOT NULL
	ALTER TABLE ConfirmMgr.USER_MASTER WITH CHECK ADD CONSTRAINT [CHK_USER_MASTER_ACTIVEFLAG] CHECK (([ACTIVE_FLAG ]= 'Y' OR [ACTIVE_FLAG ]= 'N'));
GO
IF OBJECT_ID('ConfirmMgr.USER_MASTER') IS NOT NULL
	ALTER TABLE ConfirmMgr.USER_MASTER CHECK CONSTRAINT [CHK_USER_MASTER_ACTIVEFLAG]
GO
PRINT 'CHECK CONSTRAINT CHK_USER_MASTER_ACTIVEFLAG CREATED WITH SUCCESS!!!'
GO