IF OBJECT_ID('ConfirmMgr.USER_MASTER') IS NOT NULL
	ALTER TABLE ConfirmMgr.USER_FILTERS_OPSMGR ADD CONSTRAINT [FK_USERMASTER_FILTERSOPSMGR] FOREIGN KEY ([USER_ID]) REFERENCES ConfirmMgr.USER_MASTER ([USER_ID])
GO
PRINT 'FOREIGN KEY FK_USERMASTER_FILTERSOPSMGR CREATED WITH SUCCESS!!!'
GO
