IF OBJECT_ID('ConfirmMgr.USER_MASTER') IS NOT NULL
	ALTER TABLE ConfirmMgr.USER_ROLE ADD CONSTRAINT [FK_USERROLE_USERMASTER] FOREIGN KEY ([USER_ID]) REFERENCES ConfirmMgr.USER_MASTER ([USER_ID])
GO
PRINT 'FOREIGN KEY FK_USERROLE_USERMASTER CREATED WITH SUCCESS!!!'
GO