declare 
@error_msg	varchar(4000)
BEGIN TRY
MERGE ConfirmMgr.USER_MASTER AS t
USING (SELECT DISTINCT USER_ID FROM ConfirmMgr.USER_FILTERS_OPSMGR)  AS s
ON (t.USER_ID = s.USER_ID)
	WHEN NOT MATCHED BY TARGET
		THEN INSERT (USER_ID, EMAIL_ADDRESS, CONFIRMS_GROUP_EMAIL_ADDRESS, ACTIVE_FLAG) VALUES(s.USER_ID, s.USER_ID, s.USER_ID, 'Y')
	WHEN MATCHED
		THEN UPDATE SET t.USER_ID = s.USER_ID
	OUTPUT $action, inserted.*, Deleted.*;
END TRY
BEGIN CATCH
	SELECT @error_msg = 'ERROR LINE: ' + CAST(ERROR_LINE() AS varchar) + ' MESSAGE: ' + ERROR_MESSAGE();
	THROW 51000, @error_msg, 1 
END CATCH
GO

