
IF OBJECT_ID('ConfirmMgr.USER_MASTER') IS NOT NULL
	ALTER TABLE ConfirmMgr.USER_MASTER
	ADD CONSTRAINT [PK_USER_MASTER] PRIMARY KEY CLUSTERED (	USER_ID ASC)
GO
PRINT 'PRIMARY KEY PK_USER_MASTER CREATED WITH SUCCESS!!!'
GO