IF OBJECT_ID('ConfirmMgr.USER_MASTER','U')IS NOT NULL
EXEC('DROP TABLE ConfirmMgr.USER_MASTER')
GO

CREATE TABLE ConfirmMgr.USER_MASTER
(
	USER_ID							varchar(30) NOT NULL,
	EMAIL_ADDRESS					varchar(100) NOT NULL,
	CONFIRMS_GROUP_EMAIL_ADDRESS	varchar(100) NOT NULL,
	ACTIVE_FLAG						char(1) NOT NULL
)
ON [PRIMARY]
GO
PRINT 'TABLE USER_MASTER_ACTIVEFLAG CREATED WITH SUCCESS!!!'
GO

