//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSAccess.SvcRef_Counterparty {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAgreementListRequest", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetAgreementListRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string bookingCompanyShortNameField;
        
        private string cptyShortNameField;
        
        private string tradingSystemCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string bookingCompanyShortName {
            get {
                return this.bookingCompanyShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.bookingCompanyShortNameField, value) != true)) {
                    this.bookingCompanyShortNameField = value;
                    this.RaisePropertyChanged("bookingCompanyShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cptyShortName {
            get {
                return this.cptyShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cptyShortNameField, value) != true)) {
                    this.cptyShortNameField = value;
                    this.RaisePropertyChanged("cptyShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemCode {
            get {
                return this.tradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemCodeField, value) != true)) {
                    this.tradingSystemCodeField = value;
                    this.RaisePropertyChanged("tradingSystemCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAgreementListResponse", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetAgreementListResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSAccess.SvcRef_Counterparty.agreement[] agreementsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSAccess.SvcRef_Counterparty.agreement[] agreements {
            get {
                return this.agreementsField;
            }
            set {
                if ((object.ReferenceEquals(this.agreementsField, value) != true)) {
                    this.agreementsField = value;
                    this.RaisePropertyChanged("agreements");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="agreement", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class agreement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agreementTypeCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string agreementTypeCode {
            get {
                return this.agreementTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.agreementTypeCodeField, value) != true)) {
                    this.agreementTypeCodeField = value;
                    this.RaisePropertyChanged("agreementTypeCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDocumentSendToRequest", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetDocumentSendToRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdtyCodeField;
        
        private string cptyShortNameField;
        
        private string documentTypeCodeField;
        
        private string settlementTypeCodeField;
        
        private string tradingSystemCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cdtyCode {
            get {
                return this.cdtyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.cdtyCodeField, value) != true)) {
                    this.cdtyCodeField = value;
                    this.RaisePropertyChanged("cdtyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cptyShortName {
            get {
                return this.cptyShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cptyShortNameField, value) != true)) {
                    this.cptyShortNameField = value;
                    this.RaisePropertyChanged("cptyShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string documentTypeCode {
            get {
                return this.documentTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.documentTypeCodeField, value) != true)) {
                    this.documentTypeCodeField = value;
                    this.RaisePropertyChanged("documentTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string settlementTypeCode {
            get {
                return this.settlementTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.settlementTypeCodeField, value) != true)) {
                    this.settlementTypeCodeField = value;
                    this.RaisePropertyChanged("settlementTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemCode {
            get {
                return this.tradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemCodeField, value) != true)) {
                    this.tradingSystemCodeField = value;
                    this.RaisePropertyChanged("tradingSystemCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDocumentSendToResponse", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetDocumentSendToResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSAccess.SvcRef_Counterparty.sendTo[] sendTosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSAccess.SvcRef_Counterparty.sendTo[] sendTos {
            get {
                return this.sendTosField;
            }
            set {
                if ((object.ReferenceEquals(this.sendTosField, value) != true)) {
                    this.sendTosField = value;
                    this.RaisePropertyChanged("sendTos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sendTo", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class sendTo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxLocalNumberField;
        
        private WSAccess.SvcRef_Counterparty.TransmitMethodInd transmitMethodIndField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.emailAddressField, value) != true)) {
                    this.emailAddressField = value;
                    this.RaisePropertyChanged("emailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faxAreaCode {
            get {
                return this.faxAreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.faxAreaCodeField, value) != true)) {
                    this.faxAreaCodeField = value;
                    this.RaisePropertyChanged("faxAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faxCountryCode {
            get {
                return this.faxCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.faxCountryCodeField, value) != true)) {
                    this.faxCountryCodeField = value;
                    this.RaisePropertyChanged("faxCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faxLocalNumber {
            get {
                return this.faxLocalNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.faxLocalNumberField, value) != true)) {
                    this.faxLocalNumberField = value;
                    this.RaisePropertyChanged("faxLocalNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WSAccess.SvcRef_Counterparty.TransmitMethodInd transmitMethodInd {
            get {
                return this.transmitMethodIndField;
            }
            set {
                if ((this.transmitMethodIndField.Equals(value) != true)) {
                    this.transmitMethodIndField = value;
                    this.RaisePropertyChanged("transmitMethodInd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransmitMethodInd", Namespace="http://cnf/Integration")]
    public enum TransmitMethodInd : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAX = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMAIL = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreDocumentSendToRequest", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class StoreDocumentSendToRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdtyCodeField;
        
        private string cptyShortNameField;
        
        private string documentTypeCodeField;
        
        private WSAccess.SvcRef_Counterparty.sendTo[] sendTosField;
        
        private string settlementTypeCodeField;
        
        private string tradingSystemCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cdtyCode {
            get {
                return this.cdtyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.cdtyCodeField, value) != true)) {
                    this.cdtyCodeField = value;
                    this.RaisePropertyChanged("cdtyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cptyShortName {
            get {
                return this.cptyShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cptyShortNameField, value) != true)) {
                    this.cptyShortNameField = value;
                    this.RaisePropertyChanged("cptyShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string documentTypeCode {
            get {
                return this.documentTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.documentTypeCodeField, value) != true)) {
                    this.documentTypeCodeField = value;
                    this.RaisePropertyChanged("documentTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WSAccess.SvcRef_Counterparty.sendTo[] sendTos {
            get {
                return this.sendTosField;
            }
            set {
                if ((object.ReferenceEquals(this.sendTosField, value) != true)) {
                    this.sendTosField = value;
                    this.RaisePropertyChanged("sendTos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string settlementTypeCode {
            get {
                return this.settlementTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.settlementTypeCodeField, value) != true)) {
                    this.settlementTypeCodeField = value;
                    this.RaisePropertyChanged("settlementTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemCode {
            get {
                return this.tradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemCodeField, value) != true)) {
                    this.tradingSystemCodeField = value;
                    this.RaisePropertyChanged("tradingSystemCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreDocumentSendToResponse", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class StoreDocumentSendToResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cnf/Integration", ConfigurationName="SvcRef_Counterparty.Counterparty")]
    public interface Counterparty {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/Integration/Counterparty/getAgreementList", ReplyAction="http://cnf/Integration/Counterparty/getAgreementListResponse")]
        WSAccess.SvcRef_Counterparty.GetAgreementListResponse getAgreementList(WSAccess.SvcRef_Counterparty.GetAgreementListRequest getAgreementListRequest);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://cnf/Integration/Counterparty/getAgreementList", ReplyAction="http://cnf/Integration/Counterparty/getAgreementListResponse")]
        System.IAsyncResult BegingetAgreementList(WSAccess.SvcRef_Counterparty.GetAgreementListRequest getAgreementListRequest, System.AsyncCallback callback, object asyncState);
        
        WSAccess.SvcRef_Counterparty.GetAgreementListResponse EndgetAgreementList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/Integration/Counterparty/getDocumentSendTo", ReplyAction="http://cnf/Integration/Counterparty/getDocumentSendToResponse")]
        WSAccess.SvcRef_Counterparty.GetDocumentSendToResponse getDocumentSendTo(WSAccess.SvcRef_Counterparty.GetDocumentSendToRequest getDocumentSendToRequest);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://cnf/Integration/Counterparty/getDocumentSendTo", ReplyAction="http://cnf/Integration/Counterparty/getDocumentSendToResponse")]
        System.IAsyncResult BegingetDocumentSendTo(WSAccess.SvcRef_Counterparty.GetDocumentSendToRequest getDocumentSendToRequest, System.AsyncCallback callback, object asyncState);
        
        WSAccess.SvcRef_Counterparty.GetDocumentSendToResponse EndgetDocumentSendTo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/Integration/Counterparty/storeDocumentSendTo", ReplyAction="http://cnf/Integration/Counterparty/storeDocumentSendToResponse")]
        WSAccess.SvcRef_Counterparty.StoreDocumentSendToResponse storeDocumentSendTo(WSAccess.SvcRef_Counterparty.StoreDocumentSendToRequest storeDocumentSendToRequest);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://cnf/Integration/Counterparty/storeDocumentSendTo", ReplyAction="http://cnf/Integration/Counterparty/storeDocumentSendToResponse")]
        System.IAsyncResult BeginstoreDocumentSendTo(WSAccess.SvcRef_Counterparty.StoreDocumentSendToRequest storeDocumentSendToRequest, System.AsyncCallback callback, object asyncState);
        
        WSAccess.SvcRef_Counterparty.StoreDocumentSendToResponse EndstoreDocumentSendTo(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CounterpartyChannel : WSAccess.SvcRef_Counterparty.Counterparty, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAgreementListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAgreementListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WSAccess.SvcRef_Counterparty.GetAgreementListResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WSAccess.SvcRef_Counterparty.GetAgreementListResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getDocumentSendToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getDocumentSendToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WSAccess.SvcRef_Counterparty.GetDocumentSendToResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WSAccess.SvcRef_Counterparty.GetDocumentSendToResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class storeDocumentSendToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public storeDocumentSendToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WSAccess.SvcRef_Counterparty.StoreDocumentSendToResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WSAccess.SvcRef_Counterparty.StoreDocumentSendToResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CounterpartyClient : System.ServiceModel.ClientBase<WSAccess.SvcRef_Counterparty.Counterparty>, WSAccess.SvcRef_Counterparty.Counterparty {
        
        private BeginOperationDelegate onBegingetAgreementListDelegate;
        
        private EndOperationDelegate onEndgetAgreementListDelegate;
        
        private System.Threading.SendOrPostCallback ongetAgreementListCompletedDelegate;
        
        private BeginOperationDelegate onBegingetDocumentSendToDelegate;
        
        private EndOperationDelegate onEndgetDocumentSendToDelegate;
        
        private System.Threading.SendOrPostCallback ongetDocumentSendToCompletedDelegate;
        
        private BeginOperationDelegate onBeginstoreDocumentSendToDelegate;
        
        private EndOperationDelegate onEndstoreDocumentSendToDelegate;
        
        private System.Threading.SendOrPostCallback onstoreDocumentSendToCompletedDelegate;
        
        public CounterpartyClient() {
        }
        
        public CounterpartyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CounterpartyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CounterpartyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CounterpartyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<getAgreementListCompletedEventArgs> getAgreementListCompleted;
        
        public event System.EventHandler<getDocumentSendToCompletedEventArgs> getDocumentSendToCompleted;
        
        public event System.EventHandler<storeDocumentSendToCompletedEventArgs> storeDocumentSendToCompleted;
        
        public WSAccess.SvcRef_Counterparty.GetAgreementListResponse getAgreementList(WSAccess.SvcRef_Counterparty.GetAgreementListRequest getAgreementListRequest) {
            return base.Channel.getAgreementList(getAgreementListRequest);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetAgreementList(WSAccess.SvcRef_Counterparty.GetAgreementListRequest getAgreementListRequest, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAgreementList(getAgreementListRequest, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WSAccess.SvcRef_Counterparty.GetAgreementListResponse EndgetAgreementList(System.IAsyncResult result) {
            return base.Channel.EndgetAgreementList(result);
        }
        
        private System.IAsyncResult OnBegingetAgreementList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WSAccess.SvcRef_Counterparty.GetAgreementListRequest getAgreementListRequest = ((WSAccess.SvcRef_Counterparty.GetAgreementListRequest)(inValues[0]));
            return this.BegingetAgreementList(getAgreementListRequest, callback, asyncState);
        }
        
        private object[] OnEndgetAgreementList(System.IAsyncResult result) {
            WSAccess.SvcRef_Counterparty.GetAgreementListResponse retVal = this.EndgetAgreementList(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAgreementListCompleted(object state) {
            if ((this.getAgreementListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAgreementListCompleted(this, new getAgreementListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAgreementListAsync(WSAccess.SvcRef_Counterparty.GetAgreementListRequest getAgreementListRequest) {
            this.getAgreementListAsync(getAgreementListRequest, null);
        }
        
        public void getAgreementListAsync(WSAccess.SvcRef_Counterparty.GetAgreementListRequest getAgreementListRequest, object userState) {
            if ((this.onBegingetAgreementListDelegate == null)) {
                this.onBegingetAgreementListDelegate = new BeginOperationDelegate(this.OnBegingetAgreementList);
            }
            if ((this.onEndgetAgreementListDelegate == null)) {
                this.onEndgetAgreementListDelegate = new EndOperationDelegate(this.OnEndgetAgreementList);
            }
            if ((this.ongetAgreementListCompletedDelegate == null)) {
                this.ongetAgreementListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAgreementListCompleted);
            }
            base.InvokeAsync(this.onBegingetAgreementListDelegate, new object[] {
                        getAgreementListRequest}, this.onEndgetAgreementListDelegate, this.ongetAgreementListCompletedDelegate, userState);
        }
        
        public WSAccess.SvcRef_Counterparty.GetDocumentSendToResponse getDocumentSendTo(WSAccess.SvcRef_Counterparty.GetDocumentSendToRequest getDocumentSendToRequest) {
            return base.Channel.getDocumentSendTo(getDocumentSendToRequest);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetDocumentSendTo(WSAccess.SvcRef_Counterparty.GetDocumentSendToRequest getDocumentSendToRequest, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetDocumentSendTo(getDocumentSendToRequest, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WSAccess.SvcRef_Counterparty.GetDocumentSendToResponse EndgetDocumentSendTo(System.IAsyncResult result) {
            return base.Channel.EndgetDocumentSendTo(result);
        }
        
        private System.IAsyncResult OnBegingetDocumentSendTo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WSAccess.SvcRef_Counterparty.GetDocumentSendToRequest getDocumentSendToRequest = ((WSAccess.SvcRef_Counterparty.GetDocumentSendToRequest)(inValues[0]));
            return this.BegingetDocumentSendTo(getDocumentSendToRequest, callback, asyncState);
        }
        
        private object[] OnEndgetDocumentSendTo(System.IAsyncResult result) {
            WSAccess.SvcRef_Counterparty.GetDocumentSendToResponse retVal = this.EndgetDocumentSendTo(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetDocumentSendToCompleted(object state) {
            if ((this.getDocumentSendToCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getDocumentSendToCompleted(this, new getDocumentSendToCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getDocumentSendToAsync(WSAccess.SvcRef_Counterparty.GetDocumentSendToRequest getDocumentSendToRequest) {
            this.getDocumentSendToAsync(getDocumentSendToRequest, null);
        }
        
        public void getDocumentSendToAsync(WSAccess.SvcRef_Counterparty.GetDocumentSendToRequest getDocumentSendToRequest, object userState) {
            if ((this.onBegingetDocumentSendToDelegate == null)) {
                this.onBegingetDocumentSendToDelegate = new BeginOperationDelegate(this.OnBegingetDocumentSendTo);
            }
            if ((this.onEndgetDocumentSendToDelegate == null)) {
                this.onEndgetDocumentSendToDelegate = new EndOperationDelegate(this.OnEndgetDocumentSendTo);
            }
            if ((this.ongetDocumentSendToCompletedDelegate == null)) {
                this.ongetDocumentSendToCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDocumentSendToCompleted);
            }
            base.InvokeAsync(this.onBegingetDocumentSendToDelegate, new object[] {
                        getDocumentSendToRequest}, this.onEndgetDocumentSendToDelegate, this.ongetDocumentSendToCompletedDelegate, userState);
        }
        
        public WSAccess.SvcRef_Counterparty.StoreDocumentSendToResponse storeDocumentSendTo(WSAccess.SvcRef_Counterparty.StoreDocumentSendToRequest storeDocumentSendToRequest) {
            return base.Channel.storeDocumentSendTo(storeDocumentSendToRequest);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginstoreDocumentSendTo(WSAccess.SvcRef_Counterparty.StoreDocumentSendToRequest storeDocumentSendToRequest, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginstoreDocumentSendTo(storeDocumentSendToRequest, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WSAccess.SvcRef_Counterparty.StoreDocumentSendToResponse EndstoreDocumentSendTo(System.IAsyncResult result) {
            return base.Channel.EndstoreDocumentSendTo(result);
        }
        
        private System.IAsyncResult OnBeginstoreDocumentSendTo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WSAccess.SvcRef_Counterparty.StoreDocumentSendToRequest storeDocumentSendToRequest = ((WSAccess.SvcRef_Counterparty.StoreDocumentSendToRequest)(inValues[0]));
            return this.BeginstoreDocumentSendTo(storeDocumentSendToRequest, callback, asyncState);
        }
        
        private object[] OnEndstoreDocumentSendTo(System.IAsyncResult result) {
            WSAccess.SvcRef_Counterparty.StoreDocumentSendToResponse retVal = this.EndstoreDocumentSendTo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnstoreDocumentSendToCompleted(object state) {
            if ((this.storeDocumentSendToCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.storeDocumentSendToCompleted(this, new storeDocumentSendToCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void storeDocumentSendToAsync(WSAccess.SvcRef_Counterparty.StoreDocumentSendToRequest storeDocumentSendToRequest) {
            this.storeDocumentSendToAsync(storeDocumentSendToRequest, null);
        }
        
        public void storeDocumentSendToAsync(WSAccess.SvcRef_Counterparty.StoreDocumentSendToRequest storeDocumentSendToRequest, object userState) {
            if ((this.onBeginstoreDocumentSendToDelegate == null)) {
                this.onBeginstoreDocumentSendToDelegate = new BeginOperationDelegate(this.OnBeginstoreDocumentSendTo);
            }
            if ((this.onEndstoreDocumentSendToDelegate == null)) {
                this.onEndstoreDocumentSendToDelegate = new EndOperationDelegate(this.OnEndstoreDocumentSendTo);
            }
            if ((this.onstoreDocumentSendToCompletedDelegate == null)) {
                this.onstoreDocumentSendToCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnstoreDocumentSendToCompleted);
            }
            base.InvokeAsync(this.onBeginstoreDocumentSendToDelegate, new object[] {
                        storeDocumentSendToRequest}, this.onEndstoreDocumentSendToDelegate, this.onstoreDocumentSendToCompletedDelegate, userState);
        }
    }
}
