//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTester.CounterpartyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAgreementListRequest", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetAgreementListRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string bookingCompanyShortNameField;
        
        private string cptyShortNameField;
        
        private string tradingSystemCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string bookingCompanyShortName {
            get {
                return this.bookingCompanyShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.bookingCompanyShortNameField, value) != true)) {
                    this.bookingCompanyShortNameField = value;
                    this.RaisePropertyChanged("bookingCompanyShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cptyShortName {
            get {
                return this.cptyShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cptyShortNameField, value) != true)) {
                    this.cptyShortNameField = value;
                    this.RaisePropertyChanged("cptyShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemCode {
            get {
                return this.tradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemCodeField, value) != true)) {
                    this.tradingSystemCodeField = value;
                    this.RaisePropertyChanged("tradingSystemCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAgreementListResponse", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetAgreementListResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServiceTester.CounterpartyService.agreement[] agreementsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceTester.CounterpartyService.agreement[] agreements {
            get {
                return this.agreementsField;
            }
            set {
                if ((object.ReferenceEquals(this.agreementsField, value) != true)) {
                    this.agreementsField = value;
                    this.RaisePropertyChanged("agreements");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="agreement", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class agreement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agreementTypeCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string agreementTypeCode {
            get {
                return this.agreementTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.agreementTypeCodeField, value) != true)) {
                    this.agreementTypeCodeField = value;
                    this.RaisePropertyChanged("agreementTypeCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDocumentSendToRequest", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetDocumentSendToRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdtyCodeField;
        
        private string cptyShortNameField;
        
        private string documentTypeCodeField;
        
        private string settlementTypeCodeField;
        
        private string tradingSystemCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cdtyCode {
            get {
                return this.cdtyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.cdtyCodeField, value) != true)) {
                    this.cdtyCodeField = value;
                    this.RaisePropertyChanged("cdtyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cptyShortName {
            get {
                return this.cptyShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cptyShortNameField, value) != true)) {
                    this.cptyShortNameField = value;
                    this.RaisePropertyChanged("cptyShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string documentTypeCode {
            get {
                return this.documentTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.documentTypeCodeField, value) != true)) {
                    this.documentTypeCodeField = value;
                    this.RaisePropertyChanged("documentTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string settlementTypeCode {
            get {
                return this.settlementTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.settlementTypeCodeField, value) != true)) {
                    this.settlementTypeCodeField = value;
                    this.RaisePropertyChanged("settlementTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemCode {
            get {
                return this.tradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemCodeField, value) != true)) {
                    this.tradingSystemCodeField = value;
                    this.RaisePropertyChanged("tradingSystemCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDocumentSendToResponse", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetDocumentSendToResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServiceTester.CounterpartyService.sendTo[] sendTosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceTester.CounterpartyService.sendTo[] sendTos {
            get {
                return this.sendTosField;
            }
            set {
                if ((object.ReferenceEquals(this.sendTosField, value) != true)) {
                    this.sendTosField = value;
                    this.RaisePropertyChanged("sendTos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sendTo", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class sendTo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxLocalNumberField;
        
        private WebServiceTester.CounterpartyService.TransmitMethodInd transmitMethodIndField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.emailAddressField, value) != true)) {
                    this.emailAddressField = value;
                    this.RaisePropertyChanged("emailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faxAreaCode {
            get {
                return this.faxAreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.faxAreaCodeField, value) != true)) {
                    this.faxAreaCodeField = value;
                    this.RaisePropertyChanged("faxAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faxCountryCode {
            get {
                return this.faxCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.faxCountryCodeField, value) != true)) {
                    this.faxCountryCodeField = value;
                    this.RaisePropertyChanged("faxCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faxLocalNumber {
            get {
                return this.faxLocalNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.faxLocalNumberField, value) != true)) {
                    this.faxLocalNumberField = value;
                    this.RaisePropertyChanged("faxLocalNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebServiceTester.CounterpartyService.TransmitMethodInd transmitMethodInd {
            get {
                return this.transmitMethodIndField;
            }
            set {
                if ((this.transmitMethodIndField.Equals(value) != true)) {
                    this.transmitMethodIndField = value;
                    this.RaisePropertyChanged("transmitMethodInd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransmitMethodInd", Namespace="http://cnf/Integration")]
    public enum TransmitMethodInd : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAX = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMAIL = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreDocumentSendToRequest", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class StoreDocumentSendToRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cdtyCodeField;
        
        private string cptyShortNameField;
        
        private string documentTypeCodeField;
        
        private WebServiceTester.CounterpartyService.sendTo[] sendTosField;
        
        private string settlementTypeCodeField;
        
        private string tradingSystemCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cdtyCode {
            get {
                return this.cdtyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.cdtyCodeField, value) != true)) {
                    this.cdtyCodeField = value;
                    this.RaisePropertyChanged("cdtyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cptyShortName {
            get {
                return this.cptyShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.cptyShortNameField, value) != true)) {
                    this.cptyShortNameField = value;
                    this.RaisePropertyChanged("cptyShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string documentTypeCode {
            get {
                return this.documentTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.documentTypeCodeField, value) != true)) {
                    this.documentTypeCodeField = value;
                    this.RaisePropertyChanged("documentTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebServiceTester.CounterpartyService.sendTo[] sendTos {
            get {
                return this.sendTosField;
            }
            set {
                if ((object.ReferenceEquals(this.sendTosField, value) != true)) {
                    this.sendTosField = value;
                    this.RaisePropertyChanged("sendTos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string settlementTypeCode {
            get {
                return this.settlementTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.settlementTypeCodeField, value) != true)) {
                    this.settlementTypeCodeField = value;
                    this.RaisePropertyChanged("settlementTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemCode {
            get {
                return this.tradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemCodeField, value) != true)) {
                    this.tradingSystemCodeField = value;
                    this.RaisePropertyChanged("tradingSystemCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreDocumentSendToResponse", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class StoreDocumentSendToResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cnf/Integration", ConfigurationName="CounterpartyService.Counterparty")]
    public interface Counterparty {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/Integration/Counterparty/getAgreementList", ReplyAction="http://cnf/Integration/Counterparty/getAgreementListResponse")]
        WebServiceTester.CounterpartyService.GetAgreementListResponse getAgreementList(WebServiceTester.CounterpartyService.GetAgreementListRequest getAgreementListRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/Integration/Counterparty/getAgreementList", ReplyAction="http://cnf/Integration/Counterparty/getAgreementListResponse")]
        System.Threading.Tasks.Task<WebServiceTester.CounterpartyService.GetAgreementListResponse> getAgreementListAsync(WebServiceTester.CounterpartyService.GetAgreementListRequest getAgreementListRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/Integration/Counterparty/getDocumentSendTo", ReplyAction="http://cnf/Integration/Counterparty/getDocumentSendToResponse")]
        WebServiceTester.CounterpartyService.GetDocumentSendToResponse getDocumentSendTo(WebServiceTester.CounterpartyService.GetDocumentSendToRequest getDocumentSendToRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/Integration/Counterparty/getDocumentSendTo", ReplyAction="http://cnf/Integration/Counterparty/getDocumentSendToResponse")]
        System.Threading.Tasks.Task<WebServiceTester.CounterpartyService.GetDocumentSendToResponse> getDocumentSendToAsync(WebServiceTester.CounterpartyService.GetDocumentSendToRequest getDocumentSendToRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/Integration/Counterparty/storeDocumentSendTo", ReplyAction="http://cnf/Integration/Counterparty/storeDocumentSendToResponse")]
        WebServiceTester.CounterpartyService.StoreDocumentSendToResponse storeDocumentSendTo(WebServiceTester.CounterpartyService.StoreDocumentSendToRequest storeDocumentSendToRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/Integration/Counterparty/storeDocumentSendTo", ReplyAction="http://cnf/Integration/Counterparty/storeDocumentSendToResponse")]
        System.Threading.Tasks.Task<WebServiceTester.CounterpartyService.StoreDocumentSendToResponse> storeDocumentSendToAsync(WebServiceTester.CounterpartyService.StoreDocumentSendToRequest storeDocumentSendToRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CounterpartyChannel : WebServiceTester.CounterpartyService.Counterparty, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CounterpartyClient : System.ServiceModel.ClientBase<WebServiceTester.CounterpartyService.Counterparty>, WebServiceTester.CounterpartyService.Counterparty {
        
        public CounterpartyClient() {
        }
        
        public CounterpartyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CounterpartyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CounterpartyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CounterpartyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebServiceTester.CounterpartyService.GetAgreementListResponse getAgreementList(WebServiceTester.CounterpartyService.GetAgreementListRequest getAgreementListRequest) {
            return base.Channel.getAgreementList(getAgreementListRequest);
        }
        
        public System.Threading.Tasks.Task<WebServiceTester.CounterpartyService.GetAgreementListResponse> getAgreementListAsync(WebServiceTester.CounterpartyService.GetAgreementListRequest getAgreementListRequest) {
            return base.Channel.getAgreementListAsync(getAgreementListRequest);
        }
        
        public WebServiceTester.CounterpartyService.GetDocumentSendToResponse getDocumentSendTo(WebServiceTester.CounterpartyService.GetDocumentSendToRequest getDocumentSendToRequest) {
            return base.Channel.getDocumentSendTo(getDocumentSendToRequest);
        }
        
        public System.Threading.Tasks.Task<WebServiceTester.CounterpartyService.GetDocumentSendToResponse> getDocumentSendToAsync(WebServiceTester.CounterpartyService.GetDocumentSendToRequest getDocumentSendToRequest) {
            return base.Channel.getDocumentSendToAsync(getDocumentSendToRequest);
        }
        
        public WebServiceTester.CounterpartyService.StoreDocumentSendToResponse storeDocumentSendTo(WebServiceTester.CounterpartyService.StoreDocumentSendToRequest storeDocumentSendToRequest) {
            return base.Channel.storeDocumentSendTo(storeDocumentSendToRequest);
        }
        
        public System.Threading.Tasks.Task<WebServiceTester.CounterpartyService.StoreDocumentSendToResponse> storeDocumentSendToAsync(WebServiceTester.CounterpartyService.StoreDocumentSendToRequest storeDocumentSendToRequest) {
            return base.Channel.storeDocumentSendToAsync(storeDocumentSendToRequest);
        }
    }
}
