//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.XtraBars;
using DevExpress.XtraBars.Ribbon;
using DevExpress.XtraEditors;
using System;
using System.ComponentModel;
using System.Diagnostics;


namespace NSRabbit_test {
    
    public partial class rabbit_testForm : RibbonForm {
        #region fields
        /// <summary>
        /// Required designer variable.
        /// </summary>
        IContainer components = null;
        RibbonControl ribbonControl;
        RibbonPage ribbonPage;
        RibbonPageGroup ribbonPageGroup;
        BarButtonItem bbExit;
        BarButtonItem bbAbout;
        RibbonStatusBar ribbonStatusBar;
        #endregion
        #region Windows Form Designer generated code
        /// <summary>Required method for Designer support</summary>
        void InitializeComponent() {
            this.ribbonControl = new DevExpress.XtraBars.Ribbon.RibbonControl();
            this.bbExit = new DevExpress.XtraBars.BarButtonItem();
            this.bbAbout = new DevExpress.XtraBars.BarButtonItem();
            this.bciCreateSendQ = new DevExpress.XtraBars.BarCheckItem();
            this.bciCreateListenQ = new DevExpress.XtraBars.BarCheckItem();
            this.bciGenMsg = new DevExpress.XtraBars.BarCheckItem();
            this.ribbonPage = new DevExpress.XtraBars.Ribbon.RibbonPage();
            this.ribbonPageGroup = new DevExpress.XtraBars.Ribbon.RibbonPageGroup();
            this.ribbonStatusBar = new DevExpress.XtraBars.Ribbon.RibbonStatusBar();
            this.splitContainerControl1 = new DevExpress.XtraEditors.SplitContainerControl();
            this.meOutput = new DevExpress.XtraEditors.MemoEdit();
            this.meErrors = new DevExpress.XtraEditors.MemoEdit();
            this.bbiMelvin = new DevExpress.XtraBars.BarButtonItem();
            ((System.ComponentModel.ISupportInitialize)(this.ribbonControl)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerControl1)).BeginInit();
            this.splitContainerControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.meOutput.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.meErrors.Properties)).BeginInit();
            this.SuspendLayout();
            // 
            // ribbonControl
            // 
            this.ribbonControl.ExpandCollapseItem.Id = 0;
            this.ribbonControl.Items.AddRange(new DevExpress.XtraBars.BarItem[] {
            this.ribbonControl.ExpandCollapseItem,
            this.bbExit,
            this.bbAbout,
            this.bciCreateSendQ,
            this.bciCreateListenQ,
            this.bciGenMsg,
            this.bbiMelvin});
            this.ribbonControl.Location = new System.Drawing.Point(0, 0);
            this.ribbonControl.MaxItemId = 10;
            this.ribbonControl.Name = "ribbonControl";
            this.ribbonControl.PageHeaderItemLinks.Add(this.bbAbout);
            this.ribbonControl.Pages.AddRange(new DevExpress.XtraBars.Ribbon.RibbonPage[] {
            this.ribbonPage});
            this.ribbonControl.Size = new System.Drawing.Size(464, 155);
            this.ribbonControl.StatusBar = this.ribbonStatusBar;
            // 
            // bbExit
            // 
            this.bbExit.Caption = "Exit";
            this.bbExit.Id = 1;
            this.bbExit.Name = "bbExit";
            this.bbExit.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.exitApp);
            // 
            // bbAbout
            // 
            this.bbAbout.Id = 2;
            this.bbAbout.Name = "bbAbout";
            this.bbAbout.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.showAbout);
            // 
            // bciCreateSendQ
            // 
            this.bciCreateSendQ.Caption = "Create Send queue";
            this.bciCreateSendQ.Id = 6;
            this.bciCreateSendQ.Name = "bciCreateSendQ";
            this.bciCreateSendQ.CheckedChanged += new DevExpress.XtraBars.ItemClickEventHandler(this.bciCreateSendQ_CheckedChanged);
            // 
            // bciCreateListenQ
            // 
            this.bciCreateListenQ.Caption = "Create listener queue";
            this.bciCreateListenQ.Id = 7;
            this.bciCreateListenQ.Name = "bciCreateListenQ";
            this.bciCreateListenQ.CheckedChanged += new DevExpress.XtraBars.ItemClickEventHandler(this.bciCreateListenQ_CheckedChanged);
            // 
            // bciGenMsg
            // 
            this.bciGenMsg.Caption = "Generate messages";
            this.bciGenMsg.Id = 8;
            this.bciGenMsg.Name = "bciGenMsg";
            this.bciGenMsg.CheckedChanged += new DevExpress.XtraBars.ItemClickEventHandler(this.bciGenMsg_CheckedChanged);
            // 
            // ribbonPage
            // 
            this.ribbonPage.Groups.AddRange(new DevExpress.XtraBars.Ribbon.RibbonPageGroup[] {
            this.ribbonPageGroup});
            this.ribbonPage.Name = "ribbonPage";
            this.ribbonPage.Text = "File";
            // 
            // ribbonPageGroup
            // 
            this.ribbonPageGroup.ItemLinks.Add(this.bciCreateSendQ);
            this.ribbonPageGroup.ItemLinks.Add(this.bciGenMsg);
            this.ribbonPageGroup.ItemLinks.Add(this.bciCreateListenQ);
            this.ribbonPageGroup.ItemLinks.Add(this.bbiMelvin);
            this.ribbonPageGroup.ItemLinks.Add(this.bbExit);
            this.ribbonPageGroup.Name = "ribbonPageGroup";
            this.ribbonPageGroup.Text = "File";
            // 
            // ribbonStatusBar
            // 
            this.ribbonStatusBar.Location = new System.Drawing.Point(0, 325);
            this.ribbonStatusBar.Name = "ribbonStatusBar";
            this.ribbonStatusBar.Ribbon = this.ribbonControl;
            this.ribbonStatusBar.Size = new System.Drawing.Size(464, 31);
            // 
            // splitContainerControl1
            // 
            this.splitContainerControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainerControl1.Horizontal = false;
            this.splitContainerControl1.Location = new System.Drawing.Point(0, 155);
            this.splitContainerControl1.Name = "splitContainerControl1";
            this.splitContainerControl1.Panel1.Controls.Add(this.meOutput);
            this.splitContainerControl1.Panel1.Text = "Panel1";
            this.splitContainerControl1.Panel2.Controls.Add(this.meErrors);
            this.splitContainerControl1.Panel2.Text = "Panel2";
            this.splitContainerControl1.Size = new System.Drawing.Size(464, 170);
            this.splitContainerControl1.SplitterPosition = 85;
            this.splitContainerControl1.TabIndex = 2;
            this.splitContainerControl1.Text = "splitContainerControl1";
            // 
            // meOutput
            // 
            this.meOutput.Dock = System.Windows.Forms.DockStyle.Fill;
            this.meOutput.Location = new System.Drawing.Point(0, 0);
            this.meOutput.MenuManager = this.ribbonControl;
            this.meOutput.Name = "meOutput";
            this.meOutput.Size = new System.Drawing.Size(464, 85);
            this.meOutput.TabIndex = 0;
            // 
            // meErrors
            // 
            this.meErrors.Dock = System.Windows.Forms.DockStyle.Fill;
            this.meErrors.Location = new System.Drawing.Point(0, 0);
            this.meErrors.MenuManager = this.ribbonControl;
            this.meErrors.Name = "meErrors";
            this.meErrors.Size = new System.Drawing.Size(464, 80);
            this.meErrors.TabIndex = 0;
            // 
            // bbiMelvin
            // 
            this.bbiMelvin.Caption = "Melvin";
            this.bbiMelvin.Id = 9;
            this.bbiMelvin.Name = "bbiMelvin";
            this.bbiMelvin.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.bbiMelvin_ItemClick);
            // 
            // rabbit_testForm
            // 
            this.ClientSize = new System.Drawing.Size(464, 356);
            this.Controls.Add(this.splitContainerControl1);
            this.Controls.Add(this.ribbonStatusBar);
            this.Controls.Add(this.ribbonControl);
            this.Name = "rabbit_testForm";
            this.Ribbon = this.ribbonControl;
            this.RibbonVisibility = DevExpress.XtraBars.Ribbon.RibbonVisibility.Visible;
            this.StatusBar = this.ribbonStatusBar;
            this.Load += new System.EventHandler(this.formLoad);
            ((System.ComponentModel.ISupportInitialize)(this.ribbonControl)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerControl1)).EndInit();
            this.splitContainerControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.meOutput.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.meErrors.Properties)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        #endregion
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing) {
            if (disposing) {
                if ((components != null)) {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }
         BarCheckItem bciCreateSendQ;
         BarCheckItem bciCreateListenQ;
         BarCheckItem bciGenMsg;
         SplitContainerControl splitContainerControl1;
         MemoEdit meOutput;
         MemoEdit meErrors;
         BarButtonItem bbiMelvin;
    }
}
