ALTER TABLE ConfirmMgr.XMIT_REQUEST 
alter column SENT_BY_USER varchar(30);
GO
PRINT 'COLUMN SENT_BY_USER ON TABLE XMIT_REQUEST ALTERED'
GO
ALTER TABLE ConfirmMgr.TRADE_RQMT_CONFIRM_CREATOR 
alter column USER_ID varchar(30);
GO
PRINT 'COLUMN USER_ID ON TABLE TRADE_RQMT_CONFIRM_CREATOR ALTERED'
GO
ALTER TABLE ConfirmMgr.TRADE_RQMT_CONFIRM_CREATOR_JN 
alter column USER_ID varchar(30);
GO
PRINT 'COLUMN USER_ID ON TABLE TRADE_RQMT_CONFIRM_CREATOR_JN ALTERED'
GO
ALTER TABLE ConfirmMgr.USER_FILTERS_OPSMGR 
alter column USER_ID varchar(30);
GO
PRINT 'COLUMN USER_ID ON TABLE USER_FILTERS_OPSMGR ALTERED'
GO
PRINT 'ALTERING TABLE USER_ROLE..................................'
GO
ALTER TABLE ConfirmMgr.USER_ROLE
DROP CONSTRAINT PK_USER_ROLE
GO
PRINT 'PK_USERROLE_ROLE DROPPED ON TABLE USER_ROLE'
GO
ALTER TABLE ConfirmMgr.USER_ROLE
DROP CONSTRAINT FK_USERROLE_ROLE
GO
PRINT 'FK_USERROLE_ROLE DROPPED ON TABLE USER_ROLE'
GO
ALTER TABLE ConfirmMgr.USER_ROLE 
alter column USER_ID varchar(30) NOT NULL;
GO
PRINT 'COLUMN USER_ID ON TABLE USER_ROLE ALTERED'
GO
ALTER TABLE ConfirmMgr.USER_ROLE
ADD CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ID, ROLE_CODE)
GO
PRINT 'PK_USERROLE_ROLE RE-CREATED ON TABLE USER_ROLE'
GO
ALTER TABLE ConfirmMgr.USER_ROLE WITH CHECK ADD CONSTRAINT FK_USERROLE_ROLE FOREIGN KEY(ROLE_CODE)
REFERENCES ConfirmMgr.ROLE (CODE)
GO
PRINT 'FK_USERROLE_ROLE RE-CREATED ON TABLE USER_ROLE'
GO
PRINT 'ALTER TABLE USER_ROLE FINISHED............................'
GO
ALTER TABLE ConfirmMgr.USER_ROLE_JN 
alter column USER_ID varchar(30);
GO
PRINT 'COLUMN USER_ID ON TABLE USER_ROLE_JN ALTERED'
GO
