//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSAccess.VaultSvcClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadDocumentRequest", Namespace="http://dms/Integration")]
    [System.SerializableAttribute()]
    public partial class UploadDocumentRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeedTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectFormatIndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ObjectStreamField;
        
        private string TradingSystemCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentKey {
            get {
                return this.DocumentKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentKeyField, value) != true)) {
                    this.DocumentKeyField = value;
                    this.RaisePropertyChanged("DocumentKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTypeField, value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeedType {
            get {
                return this.FeedTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedTypeField, value) != true)) {
                    this.FeedTypeField = value;
                    this.RaisePropertyChanged("FeedType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectFormatInd {
            get {
                return this.ObjectFormatIndField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectFormatIndField, value) != true)) {
                    this.ObjectFormatIndField = value;
                    this.RaisePropertyChanged("ObjectFormatInd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ObjectStream {
            get {
                return this.ObjectStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectStreamField, value) != true)) {
                    this.ObjectStreamField = value;
                    this.RaisePropertyChanged("ObjectStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TradingSystemCode {
            get {
                return this.TradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TradingSystemCodeField, value) != true)) {
                    this.TradingSystemCodeField = value;
                    this.RaisePropertyChanged("TradingSystemCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadDocumentResponse", Namespace="http://dms/Integration")]
    [System.SerializableAttribute()]
    public partial class UploadDocumentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string StatusField;
        
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVersionInfoForDocumentRequest", Namespace="http://dms/Integration")]
    [System.SerializableAttribute()]
    public partial class GetVersionInfoForDocumentRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSAccess.VaultSvcClient.ContractInfo DocInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeedTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradingSystemCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSAccess.VaultSvcClient.ContractInfo DocInfo {
            get {
                return this.DocInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocInfoField, value) != true)) {
                    this.DocInfoField = value;
                    this.RaisePropertyChanged("DocInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentKey {
            get {
                return this.DocumentKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentKeyField, value) != true)) {
                    this.DocumentKeyField = value;
                    this.RaisePropertyChanged("DocumentKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeedType {
            get {
                return this.FeedTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedTypeField, value) != true)) {
                    this.FeedTypeField = value;
                    this.RaisePropertyChanged("FeedType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradingSystemCode {
            get {
                return this.TradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TradingSystemCodeField, value) != true)) {
                    this.TradingSystemCodeField = value;
                    this.RaisePropertyChanged("TradingSystemCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractInfo", Namespace="http://dms/Integration")]
    [System.SerializableAttribute()]
    public partial class ContractInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingCompShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CmdtyGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLatestVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfitCenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TradeNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraderInitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingCompShortName {
            get {
                return this.BookingCompShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingCompShortNameField, value) != true)) {
                    this.BookingCompShortNameField = value;
                    this.RaisePropertyChanged("BookingCompShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CmdtyGroup {
            get {
                return this.CmdtyGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.CmdtyGroupField, value) != true)) {
                    this.CmdtyGroupField = value;
                    this.RaisePropertyChanged("CmdtyGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocID {
            get {
                return this.DocIDField;
            }
            set {
                if ((this.DocIDField.Equals(value) != true)) {
                    this.DocIDField = value;
                    this.RaisePropertyChanged("DocID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocName {
            get {
                return this.DocNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNameField, value) != true)) {
                    this.DocNameField = value;
                    this.RaisePropertyChanged("DocName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocType {
            get {
                return this.DocTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocTypeField, value) != true)) {
                    this.DocTypeField = value;
                    this.RaisePropertyChanged("DocType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileType {
            get {
                return this.FileTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FileTypeField, value) != true)) {
                    this.FileTypeField = value;
                    this.RaisePropertyChanged("FileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLatestVersion {
            get {
                return this.IsLatestVersionField;
            }
            set {
                if ((this.IsLatestVersionField.Equals(value) != true)) {
                    this.IsLatestVersionField = value;
                    this.RaisePropertyChanged("IsLatestVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfitCenter {
            get {
                return this.ProfitCenterField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfitCenterField, value) != true)) {
                    this.ProfitCenterField = value;
                    this.RaisePropertyChanged("ProfitCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TradeNum {
            get {
                return this.TradeNumField;
            }
            set {
                if ((this.TradeNumField.Equals(value) != true)) {
                    this.TradeNumField = value;
                    this.RaisePropertyChanged("TradeNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraderInit {
            get {
                return this.TraderInitField;
            }
            set {
                if ((object.ReferenceEquals(this.TraderInitField, value) != true)) {
                    this.TraderInitField = value;
                    this.RaisePropertyChanged("TraderInit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionNum {
            get {
                return this.VersionNumField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionNumField, value) != true)) {
                    this.VersionNumField = value;
                    this.RaisePropertyChanged("VersionNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVersionInfoForResponse", Namespace="http://dms/Integration")]
    [System.SerializableAttribute()]
    public partial class GetVersionInfoForResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSAccess.VaultSvcClient.ContractInfo[] QueryResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSAccess.VaultSvcClient.ContractInfo[] QueryResult {
            get {
                return this.QueryResultField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryResultField, value) != true)) {
                    this.QueryResultField = value;
                    this.RaisePropertyChanged("QueryResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDocInfoForQueryRequest", Namespace="http://dms/Integration")]
    [System.SerializableAttribute()]
    public partial class GetDocInfoForQueryRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeedTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> QueryValuesField;
        
        private string TradingSystemCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentKey {
            get {
                return this.DocumentKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentKeyField, value) != true)) {
                    this.DocumentKeyField = value;
                    this.RaisePropertyChanged("DocumentKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeedType {
            get {
                return this.FeedTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedTypeField, value) != true)) {
                    this.FeedTypeField = value;
                    this.RaisePropertyChanged("FeedType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> QueryValues {
            get {
                return this.QueryValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryValuesField, value) != true)) {
                    this.QueryValuesField = value;
                    this.RaisePropertyChanged("QueryValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TradingSystemCode {
            get {
                return this.TradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TradingSystemCodeField, value) != true)) {
                    this.TradingSystemCodeField = value;
                    this.RaisePropertyChanged("TradingSystemCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDocInfoForQueryResponse", Namespace="http://dms/Integration")]
    [System.SerializableAttribute()]
    public partial class GetDocInfoForQueryResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSAccess.VaultSvcClient.ContractInfo[] QueryResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSAccess.VaultSvcClient.ContractInfo[] QueryResult {
            get {
                return this.QueryResultField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryResultField, value) != true)) {
                    this.QueryResultField = value;
                    this.RaisePropertyChanged("QueryResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDocumentForURLRequest", Namespace="http://dms/Integration")]
    [System.SerializableAttribute()]
    public partial class GetDocumentForURLRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeedTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        private string TradingSystemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentKey {
            get {
                return this.DocumentKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentKeyField, value) != true)) {
                    this.DocumentKeyField = value;
                    this.RaisePropertyChanged("DocumentKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeedType {
            get {
                return this.FeedTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedTypeField, value) != true)) {
                    this.FeedTypeField = value;
                    this.RaisePropertyChanged("FeedType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TradingSystemCode {
            get {
                return this.TradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TradingSystemCodeField, value) != true)) {
                    this.TradingSystemCodeField = value;
                    this.RaisePropertyChanged("TradingSystemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDocumentForURLResponse", Namespace="http://dms/Integration")]
    [System.SerializableAttribute()]
    public partial class GetDocumentForURLResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ObjectStreamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ObjectStream {
            get {
                return this.ObjectStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectStreamField, value) != true)) {
                    this.ObjectStreamField = value;
                    this.RaisePropertyChanged("ObjectStream");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dms/VaultService", ConfigurationName="VaultSvcClient.VaultSvc")]
    public interface VaultSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dms/VaultService/VaultSvc/UploadDocument", ReplyAction="http://dms/VaultService/VaultSvc/UploadDocumentResponse")]
        WSAccess.VaultSvcClient.UploadDocumentResponse UploadDocument(WSAccess.VaultSvcClient.UploadDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dms/VaultService/VaultSvc/GetVersionInfoForDocument", ReplyAction="http://dms/VaultService/VaultSvc/GetVersionInfoForDocumentResponse")]
        WSAccess.VaultSvcClient.GetVersionInfoForResponse GetVersionInfoForDocument(WSAccess.VaultSvcClient.GetVersionInfoForDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dms/VaultService/VaultSvc/GetDocInfoForQuery", ReplyAction="http://dms/VaultService/VaultSvc/GetDocInfoForQueryResponse")]
        WSAccess.VaultSvcClient.GetDocInfoForQueryResponse GetDocInfoForQuery(WSAccess.VaultSvcClient.GetDocInfoForQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dms/VaultService/VaultSvc/GetDocumentForURL", ReplyAction="http://dms/VaultService/VaultSvc/GetDocumentForURLResponse")]
        WSAccess.VaultSvcClient.GetDocumentForURLResponse GetDocumentForURL(WSAccess.VaultSvcClient.GetDocumentForURLRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VaultSvcChannel : WSAccess.VaultSvcClient.VaultSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VaultSvcClient : System.ServiceModel.ClientBase<WSAccess.VaultSvcClient.VaultSvc>, WSAccess.VaultSvcClient.VaultSvc {
        
        public VaultSvcClient() {
        }
        
        public VaultSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VaultSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VaultSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VaultSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WSAccess.VaultSvcClient.UploadDocumentResponse UploadDocument(WSAccess.VaultSvcClient.UploadDocumentRequest request) {
            return base.Channel.UploadDocument(request);
        }
        
        public WSAccess.VaultSvcClient.GetVersionInfoForResponse GetVersionInfoForDocument(WSAccess.VaultSvcClient.GetVersionInfoForDocumentRequest request) {
            return base.Channel.GetVersionInfoForDocument(request);
        }
        
        public WSAccess.VaultSvcClient.GetDocInfoForQueryResponse GetDocInfoForQuery(WSAccess.VaultSvcClient.GetDocInfoForQueryRequest request) {
            return base.Channel.GetDocInfoForQuery(request);
        }
        
        public WSAccess.VaultSvcClient.GetDocumentForURLResponse GetDocumentForURL(WSAccess.VaultSvcClient.GetDocumentForURLRequest request) {
            return base.Channel.GetDocumentForURL(request);
        }
    }
}
