//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSAccess.SvcRef_GetDocument {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDealSheetRequest", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetDealSheetRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string tradingSystemCodeField;
        
        private string tradingSystemKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemCode {
            get {
                return this.tradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemCodeField, value) != true)) {
                    this.tradingSystemCodeField = value;
                    this.RaisePropertyChanged("tradingSystemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemKey {
            get {
                return this.tradingSystemKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemKeyField, value) != true)) {
                    this.tradingSystemKeyField = value;
                    this.RaisePropertyChanged("tradingSystemKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDealSheetResponse", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetDealSheetResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WSAccess.SvcRef_GetDocument.ObjectFormatInd objectFormatIndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] objectStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WSAccess.SvcRef_GetDocument.ObjectFormatInd objectFormatInd {
            get {
                return this.objectFormatIndField;
            }
            set {
                if ((this.objectFormatIndField.Equals(value) != true)) {
                    this.objectFormatIndField = value;
                    this.RaisePropertyChanged("objectFormatInd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] objectStream {
            get {
                return this.objectStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.objectStreamField, value) != true)) {
                    this.objectStreamField = value;
                    this.RaisePropertyChanged("objectStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectFormatInd", Namespace="http://cnf/Integration")]
    public enum ObjectFormatInd : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDF = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCX = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HTML = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetConfirmationRequest", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetConfirmationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string templateNameField;
        
        private string tradingSystemCodeField;
        
        private string tradingSystemKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string templateName {
            get {
                return this.templateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.templateNameField, value) != true)) {
                    this.templateNameField = value;
                    this.RaisePropertyChanged("templateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemCode {
            get {
                return this.tradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemCodeField, value) != true)) {
                    this.tradingSystemCodeField = value;
                    this.RaisePropertyChanged("tradingSystemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemKey {
            get {
                return this.tradingSystemKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemKeyField, value) != true)) {
                    this.tradingSystemKeyField = value;
                    this.RaisePropertyChanged("tradingSystemKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetConfirmationResponse", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetConfirmationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool confirmCompleteFlagField;
        
        private WSAccess.SvcRef_GetDocument.ObjectFormatInd objectFormatIndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] objectStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool confirmCompleteFlag {
            get {
                return this.confirmCompleteFlagField;
            }
            set {
                if ((this.confirmCompleteFlagField.Equals(value) != true)) {
                    this.confirmCompleteFlagField = value;
                    this.RaisePropertyChanged("confirmCompleteFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WSAccess.SvcRef_GetDocument.ObjectFormatInd objectFormatInd {
            get {
                return this.objectFormatIndField;
            }
            set {
                if ((this.objectFormatIndField.Equals(value) != true)) {
                    this.objectFormatIndField = value;
                    this.RaisePropertyChanged("objectFormatInd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] objectStream {
            get {
                return this.objectStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.objectStreamField, value) != true)) {
                    this.objectStreamField = value;
                    this.RaisePropertyChanged("objectStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cnf/GetDocument", ConfigurationName="SvcRef_GetDocument.GetDocument")]
    public interface GetDocument {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/GetDocument/GetDocument/getDealSheet", ReplyAction="http://cnf/GetDocument/GetDocument/getDealSheetResponse")]
        WSAccess.SvcRef_GetDocument.GetDealSheetResponse getDealSheet(WSAccess.SvcRef_GetDocument.GetDealSheetRequest getDealSheetRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/GetDocument/GetDocument/getConfirmation", ReplyAction="http://cnf/GetDocument/GetDocument/getConfirmationResponse")]
        WSAccess.SvcRef_GetDocument.GetConfirmationResponse getConfirmation(WSAccess.SvcRef_GetDocument.GetConfirmationRequest getConfirmationRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetDocumentChannel : WSAccess.SvcRef_GetDocument.GetDocument, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDocumentClient : System.ServiceModel.ClientBase<WSAccess.SvcRef_GetDocument.GetDocument>, WSAccess.SvcRef_GetDocument.GetDocument {
        
        public GetDocumentClient() {
        }
        
        public GetDocumentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDocumentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDocumentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDocumentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WSAccess.SvcRef_GetDocument.GetDealSheetResponse getDealSheet(WSAccess.SvcRef_GetDocument.GetDealSheetRequest getDealSheetRequest) {
            return base.Channel.getDealSheet(getDealSheetRequest);
        }
        
        public WSAccess.SvcRef_GetDocument.GetConfirmationResponse getConfirmation(WSAccess.SvcRef_GetDocument.GetConfirmationRequest getConfirmationRequest) {
            return base.Channel.getConfirmation(getConfirmationRequest);
        }
    }
}
