ALTER TABLE ConfirmMgr.TRADE_RQMT_CONFIRM  WITH CHECK ADD  CONSTRAINT [CHK_PREPARER_CAN_SEND_FLAG] CHECK  (([PREPARER_CAN_SEND_FLAG]='Y' OR [PREPARER_CAN_SEND_FLAG]='N'))
GO
ALTER TABLE ConfirmMgr.TRADE_RQMT_CONFIRM CHECK CONSTRAINT [CHK_PREPARER_CAN_SEND_FLAG]
GO
PRINT 'CHECK CONSTRAINT FOR PREPARER_CAN_SEND_FLAG CREATED SUCCESSFULLY!!!'
GO