//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfirmManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sempra.ops.gs.service")]
        public string MessageUser {
            get {
                return ((string)(this["MessageUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sempra")]
        public string MessagePassword {
            get {
                return ((string)(this["MessagePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>CPTY</string>\r\n  <string>INTCO</string>\r\n  <string>REF</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection AddRqmtNoConfReason {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AddRqmtNoConfReason"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Wrong Cpty</string>
  <string>Wrong Location</string>
  <string>Wrong Volume</string>
  <string>Wrong Timing</string>
  <string>Wrong Price</string>
  <string>Other</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DisputedReasons {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DisputedReasons"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("st-mailhost")]
        public string EmailHost {
            get {
                return ((string)(this["EmailHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int EmailPort {
            get {
                return ((int)(this["EmailPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int UpdateFromCacheTimerIntervalSecs {
            get {
                return ((int)(this["UpdateFromCacheTimerIntervalSecs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cnf01inf01:61613")]
        public string MessageServer {
            get {
                return ((string)(this["MessageServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("faxgateway-CNF01@amphorainc.com")]
        public string TransmissionGatewayEmailToAddress {
            get {
                return ((string)(this["TransmissionGatewayEmailToAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Amphora Inc.-DOCIMG_RASPDFR175.lic")]
        public string LeadtoolsLicenseFile {
            get {
                return ((string)(this["LeadtoolsLicenseFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5cxfXs1TnpaXbVXDIdFzk9iRWcBBLjcIoN2W3sVpvDPvoNzYNmOr1zmYg3qhCnFE")]
        public string LeadtoolsDeveloperKey {
            get {
                return ((string)(this["LeadtoolsDeveloperKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cnf01inf01/faxgateway")]
        public string TransmissionGatewayWebAppUrl {
            get {
                return ((string)(this["TransmissionGatewayWebAppUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>amphorainc.com</string>\r\n  <string>mercuria.com</string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection EmailDomainsDevAllowSendTo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EmailDomainsDevAllowSendTo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsProductionSystem {
            get {
                return ((bool)(this["IsProductionSystem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CNF01INFDBS01\\SQLSVR11")]
        public string MSSQLServer {
            get {
                return ((string)(this["MSSQLServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cnf_mgr")]
        public string MSSQLDatabase {
            get {
                return ((string)(this["MSSQLDatabase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cnf01inf01:11111")]
        public string ExtSvcAPIBaseUrl {
            get {
                return ((string)(this["ExtSvcAPIBaseUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("affsvcprd")]
        public string ExtSvcAPIUserName {
            get {
                return ((string)(this["ExtSvcAPIUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("78ui&*UI")]
        public string ExtSvcAPIPassword {
            get {
                return ((string)(this["ExtSvcAPIPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\cnf01file01\\cnf01\\Apps\\Tools\\TestDocs\\Signatures")]
        public string InboundSignatureLocation {
            get {
                return ((string)(this["InboundSignatureLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>203-525-1100</string>\r\n  <string>203-525-1500</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FaxNumbersDevAllowSendTo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FaxNumbersDevAllowSendTo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cnf01inf01:8080/CnfMgr/RecordXmitResult.do")]
        public string TransmissionGatewayCallbackUrl {
            get {
                return ((string)(this["TransmissionGatewayCallbackUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("harley.blumenfeld@amphorainc.com")]
        public string TransmissionGatewayEmailFromAddress {
            get {
                return ((string)(this["TransmissionGatewayEmailFromAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Deprecated]")]
        public string InboundTextFilesLocation {
            get {
                return ((string)(this["InboundTextFilesLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserSettingsRootDir {
            get {
                return ((string)(this["UserSettingsRootDir"]));
            }
        }
    }
}
