//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSAccess.SvcRef_ConfirmationsManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPermissionKeysRequest", Namespace="http://cnf/ConfirmationsManager")]
    [System.SerializableAttribute()]
    public partial class GetPermissionKeysRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string applicationNameField;
        
        private string userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string applicationName {
            get {
                return this.applicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.applicationNameField, value) != true)) {
                    this.applicationNameField = value;
                    this.RaisePropertyChanged("applicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                if ((object.ReferenceEquals(this.userIdField, value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPermissionKeysResponse", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetPermissionKeysResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool superUserFlagField;
        
        private string[] permissionKeyCodesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool superUserFlag {
            get {
                return this.superUserFlagField;
            }
            set {
                if ((this.superUserFlagField.Equals(value) != true)) {
                    this.superUserFlagField = value;
                    this.RaisePropertyChanged("superUserFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string[] permissionKeyCodes {
            get {
                return this.permissionKeyCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.permissionKeyCodesField, value) != true)) {
                    this.permissionKeyCodesField = value;
                    this.RaisePropertyChanged("permissionKeyCodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetConfirmationTemplatesRequest", Namespace="http://cnf/ConfirmationsManager")]
    [System.SerializableAttribute()]
    public partial class GetConfirmationTemplatesRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string tradingSystemCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemCode {
            get {
                return this.tradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemCodeField, value) != true)) {
                    this.tradingSystemCodeField = value;
                    this.RaisePropertyChanged("tradingSystemCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetConfirmationTemplatesResponse", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class GetConfirmationTemplatesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WSAccess.SvcRef_ConfirmationsManager.confirmationTemplate[] confirmationTemplatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WSAccess.SvcRef_ConfirmationsManager.confirmationTemplate[] confirmationTemplates {
            get {
                return this.confirmationTemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.confirmationTemplatesField, value) != true)) {
                    this.confirmationTemplatesField = value;
                    this.RaisePropertyChanged("confirmationTemplates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="confirmationTemplate", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class confirmationTemplate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string templateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSAccess.SvcRef_ConfirmationsManager.attribute[] attributesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string templateName {
            get {
                return this.templateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.templateNameField, value) != true)) {
                    this.templateNameField = value;
                    this.RaisePropertyChanged("templateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public WSAccess.SvcRef_ConfirmationsManager.attribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                if ((object.ReferenceEquals(this.attributesField, value) != true)) {
                    this.attributesField = value;
                    this.RaisePropertyChanged("attributes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="attribute", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class attribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string nameField;
        
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeConfirmationStatusChangeRequest", Namespace="http://cnf/ConfirmationsManager")]
    [System.SerializableAttribute()]
    public partial class TradeConfirmationStatusChangeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string confirmationStatusCodeField;
        
        private string tradingSystemCodeField;
        
        private string tradingSystemKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string confirmationStatusCode {
            get {
                return this.confirmationStatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.confirmationStatusCodeField, value) != true)) {
                    this.confirmationStatusCodeField = value;
                    this.RaisePropertyChanged("confirmationStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemCode {
            get {
                return this.tradingSystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemCodeField, value) != true)) {
                    this.tradingSystemCodeField = value;
                    this.RaisePropertyChanged("tradingSystemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tradingSystemKey {
            get {
                return this.tradingSystemKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.tradingSystemKeyField, value) != true)) {
                    this.tradingSystemKeyField = value;
                    this.RaisePropertyChanged("tradingSystemKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeConfirmationStatusChangeResponse", Namespace="http://cnf/Integration")]
    [System.SerializableAttribute()]
    public partial class TradeConfirmationStatusChangeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cnf/ConfirmationsManager", ConfigurationName="SvcRef_ConfirmationsManager.ConfirmationsManager")]
    public interface ConfirmationsManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/ConfirmationsManager/ConfirmationsManager/getPermissionKeys", ReplyAction="http://cnf/ConfirmationsManager/ConfirmationsManager/getPermissionKeysResponse")]
        WSAccess.SvcRef_ConfirmationsManager.GetPermissionKeysResponse getPermissionKeys(WSAccess.SvcRef_ConfirmationsManager.GetPermissionKeysRequest getPermissionKeysRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/ConfirmationsManager/ConfirmationsManager/getConfirmationTemplates", ReplyAction="http://cnf/ConfirmationsManager/ConfirmationsManager/getConfirmationTemplatesResp" +
            "onse")]
        WSAccess.SvcRef_ConfirmationsManager.GetConfirmationTemplatesResponse getConfirmationTemplates(WSAccess.SvcRef_ConfirmationsManager.GetConfirmationTemplatesRequest getConfirmationTemplatesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cnf/ConfirmationsManager/ConfirmationsManager/tradeConfirmationStatusChang" +
            "e", ReplyAction="http://cnf/ConfirmationsManager/ConfirmationsManager/tradeConfirmationStatusChang" +
            "eResponse")]
        WSAccess.SvcRef_ConfirmationsManager.TradeConfirmationStatusChangeResponse tradeConfirmationStatusChange(WSAccess.SvcRef_ConfirmationsManager.TradeConfirmationStatusChangeRequest tradeConfirmationStatusChangeRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConfirmationsManagerChannel : WSAccess.SvcRef_ConfirmationsManager.ConfirmationsManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfirmationsManagerClient : System.ServiceModel.ClientBase<WSAccess.SvcRef_ConfirmationsManager.ConfirmationsManager>, WSAccess.SvcRef_ConfirmationsManager.ConfirmationsManager {
        
        public ConfirmationsManagerClient() {
        }
        
        public ConfirmationsManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfirmationsManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfirmationsManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfirmationsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WSAccess.SvcRef_ConfirmationsManager.GetPermissionKeysResponse getPermissionKeys(WSAccess.SvcRef_ConfirmationsManager.GetPermissionKeysRequest getPermissionKeysRequest) {
            return base.Channel.getPermissionKeys(getPermissionKeysRequest);
        }
        
        public WSAccess.SvcRef_ConfirmationsManager.GetConfirmationTemplatesResponse getConfirmationTemplates(WSAccess.SvcRef_ConfirmationsManager.GetConfirmationTemplatesRequest getConfirmationTemplatesRequest) {
            return base.Channel.getConfirmationTemplates(getConfirmationTemplatesRequest);
        }
        
        public WSAccess.SvcRef_ConfirmationsManager.TradeConfirmationStatusChangeResponse tradeConfirmationStatusChange(WSAccess.SvcRef_ConfirmationsManager.TradeConfirmationStatusChangeRequest tradeConfirmationStatusChangeRequest) {
            return base.Channel.tradeConfirmationStatusChange(tradeConfirmationStatusChangeRequest);
        }
    }
}
