IF OBJECT_ID('ConfirmMgr.XMIT_RESULT','U') IS NOT NULL
EXEC ('DROP TABLE ConfirmMgr.XMIT_RESULT')
GO
CREATE TABLE ConfirmMgr.XMIT_RESULT(
	[ID] [INT] NOT NULL,
	[XMIT_REQUEST_ID] [INT] NOT NULL, 
	[XMIT_STATUS_IND] [VARCHAR](1) NOT NULL,
	[XMIT_METHOD_IND] [VARCHAR](1) NOT NULL,
	[XMIT_DEST] [VARCHAR](MAX) NOT NULL,
	[XMIT_CMT] [VARCHAR](MAX) NULL,
	[XMIT_TIMESTAMP] [DATETIME2](0) NOT NULL
CONSTRAINT [PK_XMIT_RESULT] PRIMARY KEY CLUSTERED 
( 
	ID ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
) ON [PRIMARY]
GO
ALTER TABLE [ConfirmMgr].[XMIT_RESULT] ADD  CONSTRAINT [DF_XMIT_RESULT_ID]  DEFAULT (NEXT VALUE FOR [ConfirmMgr].[SEQ_XMIT_RESULT]) FOR [ID]
ALTER TABLE [ConfirmMgr].[XMIT_RESULT] WITH CHECK ADD  CONSTRAINT [FK_XMIT_RESULT_XMIT_REQUEST_ID] FOREIGN KEY([XMIT_REQUEST_ID])  REFERENCES [ConfirmMgr].[XMIT_REQUEST] ([ID])
ALTER TABLE [ConfirmMgr].[XMIT_RESULT] CHECK CONSTRAINT [FK_XMIT_RESULT_XMIT_REQUEST_ID]
ALTER TABLE [ConfirmMgr].[XMIT_RESULT] WITH CHECK ADD  CONSTRAINT [CHK_XMIT_RESULT_XMIT_STATUS_IND] CHECK  (([XMIT_STATUS_IND]='Q' OR [XMIT_STATUS_IND]='S' OR [XMIT_STATUS_IND]='F'))
ALTER TABLE [ConfirmMgr].[XMIT_RESULT] CHECK CONSTRAINT [CHK_XMIT_RESULT_XMIT_STATUS_IND]
ALTER TABLE [ConfirmMgr].[XMIT_RESULT] WITH CHECK ADD  CONSTRAINT [CHK_XMIT_RESULT_XMIT_METHOD_IND] CHECK  (([XMIT_METHOD_IND]='E' OR [XMIT_METHOD_IND]='F'))
ALTER TABLE [ConfirmMgr].[XMIT_RESULT] CHECK CONSTRAINT [CHK_XMIT_RESULT_XMIT_METHOD_IND]
GO
PRINT'TABLE XMIT_RESULT CREATED AND ALTERED SUCCESSFULLY'
GO








