IF OBJECT_ID('ConfirmMgr.XMIT_REQUEST','U') IS NOT NULL
EXEC ('DROP TABLE ConfirmMgr.XMIT_REQUEST')
GO
CREATE TABLE ConfirmMgr.XMIT_REQUEST(
	[ID] [INT] NOT NULL,
	[TRADE_RQMT_CONFIRM_ID] [INT] NULL, 
	[ASSOCIATED_DOCS_ID] [INT] NULL,
	[XMIT_METHOD_IND] [VARCHAR](1) NOT NULL,
	[XMIT_DEST] [VARCHAR](MAX) NOT NULL,
	[SENT_BY_USER] [VARCHAR](20) NOT NULL,
	[REQUEST_TIMESTAMP] [DATETIME2](0) NOT NULL
CONSTRAINT [PK_XMIT_REQUEST] PRIMARY KEY CLUSTERED 
( 
	ID ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
) 
ON [PRIMARY]
GO
ALTER TABLE [ConfirmMgr].[XMIT_REQUEST] ADD  CONSTRAINT [DF_XMIT_REQUEST_ID]  DEFAULT (NEXT VALUE FOR [ConfirmMgr].[SEQ_XMIT_REQUEST]) FOR [ID]
ALTER TABLE [ConfirmMgr].[XMIT_REQUEST] WITH CHECK ADD  CONSTRAINT [FK_XMIT_REQUEST_TRADE_RQMT_CONFIRM_ID] FOREIGN KEY([TRADE_RQMT_CONFIRM_ID])  REFERENCES [ConfirmMgr].[TRADE_RQMT_CONFIRM] ([ID])
ALTER TABLE [ConfirmMgr].[XMIT_REQUEST] CHECK CONSTRAINT [FK_XMIT_REQUEST_TRADE_RQMT_CONFIRM_ID]
ALTER TABLE [ConfirmMgr].[XMIT_REQUEST] WITH CHECK ADD  CONSTRAINT [FK_XMIT_REQUEST_ASSOC_DOCS_ID] FOREIGN KEY([ASSOCIATED_DOCS_ID])  REFERENCES [ConfirmMgr].[ASSOCIATED_DOCS] ([ID])
ALTER TABLE [ConfirmMgr].[XMIT_REQUEST] CHECK CONSTRAINT [FK_XMIT_REQUEST_ASSOC_DOCS_ID]
ALTER TABLE [ConfirmMgr].[XMIT_REQUEST] WITH CHECK ADD  CONSTRAINT [CHK_XMIT_REQUEST_XMIT_METHOD_IND] CHECK  (([XMIT_METHOD_IND]='E' OR [XMIT_METHOD_IND]='F'))
ALTER TABLE [ConfirmMgr].[XMIT_REQUEST] CHECK CONSTRAINT [CHK_XMIT_REQUEST_XMIT_METHOD_IND]
ALTER TABLE [ConfirmMgr].[XMIT_REQUEST] WITH CHECK ADD  CONSTRAINT [DF_XMIT_REQUEST_REQUEST_TIMESTAMP] DEFAULT ( GETDATE() ) FOR [REQUEST_TIMESTAMP]
GO
PRINT'TABLE XMIT_REQUEST CREATED AND ALTERED SUCCESSFULLY'
GO
