IF OBJECT_ID('ConfirmMgr.TG_TRDDATA_AER_U','TR') IS NOT NULL
EXEC ('DROP TRIGGER ConfirmMgr.TG_TRDDATA_AER_U')
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO



CREATE TRIGGER [ConfirmMgr].[TG_TRDDATA_AER_U]
ON [ConfirmMgr].[TRADE_DATA]
AFTER UPDATE
AS
/******************************************************************************
*
* AUTHOR:		JAVIER MONTERO - 08/14/2015
* DB:			SQL SERVER 2008 OR HIGHER
* VERSION:		1.0
* DESCRIPTION:  TRIGGER FOR UPDATE THE FIELD LAST_UPDATE_TIME 
				IN TABLE TRADE_SUMMARY WHEN A UPDATE ACTION IS FIRED IN
				TRADE_DATA 
* DEPENDECIES:  TABLE TRADE_SUMMARY AND TRADE_RQMT_CONFIRM IS REQUIERED
*
*******************************************************************************/
BEGIN
	UPDATE ts
		SET ts.LAST_UPDATE_TIMESTAMP_GMT = GETDATE(),
		ts.LAST_TRD_EDIT_TIMESTAMP_GMT = GETDATE(),
		ts.TRANSACTION_SEQ = next value for ConfirmMgr.SEQ_TRADE_SUMMARY_TRANSACTION
	FROM ConfirmMgr.TRADE_SUMMARY ts
		INNER JOIN inserted i
		ON ts.TRADE_ID = i.TRADE_ID
END

GO