declare 
@rows_affected		int,
@error_message		nvarchar(2000)


SET XACT_ABORT ON;
	BEGIN TRANSACTION TRAN01
		BEGIN TRY
			UPDATE ConfirmMgr.RQMT_STATUS
			SET TERMINAL_FLAG='Y'
			WHERE RQMT_CODE='XQBBP'
			AND STATUS_CODE='RECVD'
			PRINT 'RQMT_STATUS TERMINAL_FLAG UPDATED';
		
			INSERT INTO ConfirmMgr.STATUS (CODE, DESCR, ACTIVE_FLAG)
			VALUES ('DISP_CPTY','Dispusted-Awaiting Cpty','Y')
			PRINT 'NEW STATUS INSERTED ON STATUS TABLE';

			UPDATE ConfirmMgr.RQMT_STATUS
			SET ORD=ORD+1
			WHERE RQMT_CODE='XQCCP'
			AND ORD>3 AND ORD<99
			PRINT 'RQMT_STATUS ORD UPDATED FOR RQMT_CODE = XQCCP';

			INSERT INTO ConfirmMgr.RQMT_STATUS (RQMT_CODE,STATUS_CODE,ACTIVE_FLAG,ORD,TERMINAL_FLAG,PROBLEM_FLAG,GUI_COLOR_CODE)
			VALUES ('XQCCP','DISP_CPTY','Y',4,'N','Y','RED')
			PRINT 'NEW STATUS XQCCP INSERTED ON RQMY_STATUS TABLE';

			COMMIT TRANSACTION TRAN01

		END TRY
		BEGIN CATCH
			ROLLBACK TRANSACTION TRAN01
			SELECT @error_message = 'ERROR: ' + ERROR_MESSAGE() + ' LINE: ' + CAST(ERROR_LINE() AS nvarchar);
			THROW 51000, @error_message, 1
		END CATCH
	

	