@echo off
echo SET PARAMATERS TO START THE PROCESS...
REM Test parameters
IF %1NOTHING==NOTHING GOTO WARNING
IF %2NOTHING==NOTHING GOTO WARNING
IF %3NOTHING==NOTHING GOTO WARNING
IF %4NOTHING==NOTHING GOTO WARNING
REM
set ISQL="sqlcmd.exe"
set SQLCMDLOGINTIMEOUT=0
echo Validating Logs Folder
REM
cd logs
if errorlevel 1 goto dirnotexists
if exist *.log del *.log
cd ..
goto start
:dirnotexists
echo So, the folder 'logs' doesn't exist...create it now
mkdir logs

:start
echo Starting the Process at DB %4 ....
rem
echo Loading Data COLOR_TRANSLATE Table....
%ISQL% -S %1 -U %2 -P %3 -d %4 -w 250 -i REF_DATA\REF_DATA_COLOR_TRANSLATE.sql -o logs\REF_DATA_COLOR_TRANSLATE.log
echo Loading Data COLOR_TRANSLATE Table Finished....
rem
echo Loading Data CONTROL Table....
%ISQL% -S %1 -U %2 -P %3 -d %4 -w 250 -i REF_DATA\REF_DATA_CONTROL.sql -o logs\REF_DATA_CONTROL.log
echo Loading Data CONTROL Table Finished....
rem
echo Loading Data DOC_TYPE Table....
%ISQL% -S %1 -U %2 -P %3 -d %4 -w 250 -i REF_DATA\REF_DATA_DOC_TYPE.sql -o logs\REF_DATA_DOC_TYPE.log
echo Loading Data DOC_TYPE Table Finished....
rem
echo Loading Data GUI_COLOR Table....
%ISQL% -S %1 -U %2 -P %3 -d %4 -w 250 -i REF_DATA\REF_DATA_GUI_COLOR.sql -o logs\REF_DATA_GUI_COLOR.log
echo Loading Data GUI_COLOR Table Finished....
rem
echo Loading Data INB_ATTRIB Table....
%ISQL% -S %1 -U %2 -P %3 -d %4 -w 250 -i REF_DATA\REF_DATA_INB_ATTRIB.sql -o logs\REF_DATA_INB_ATTRIB.log
echo Loading Data INB_ATTRIB Table Finished....
rem
echo Loading Data ROLE Table....
%ISQL% -S %1 -U %2 -P %3 -d %4 -w 250 -i REF_DATA\REF_DATA_ROLE.sql -o logs\REF_DATA_ROLE.log
echo Loading Data ROLE Table Finished....
rem
echo Loading Data RQMT Table....
%ISQL% -S %1 -U %2 -P %3 -d %4 -w 250 -i REF_DATA\REF_DATA_RQMT.sql -o logs\REF_DATA_RQMT.log
echo Loading Data RQMT Table Finished....
rem
echo Loading Data RQMT_DOC_TYPE Table....
%ISQL% -S %1 -U %2 -P %3 -d %4 -w 250 -i REF_DATA\REF_DATA_RQMT_DOC_TYPE.sql -o logs\REF_DATA_RQMT_DOC_TYPE.log
echo Loading Data RQMT_DOC_TYPE Table Finished....
rem
echo Loading Data RQMT_STATUS Table....
%ISQL% -S %1 -U %2 -P %3 -d %4 -w 250 -i REF_DATA\REF_DATA_RQMT_STATUS.sql -o logs\REF_DATA_RQMT_STATUS.log
echo Loading Data RQMT_STATUS Table Finished....
rem
echo Loading Data STATUS Table....
%ISQL% -S %1 -U %2 -P %3 -d %4 -w 250 -i REF_DATA\REF_DATA_STATUS.sql -o logs\REF_DATA_STATUS.log
echo Loading Data STATUS Table Finished....
rem


echo Process Finished in DB %4 at Server %1 !!!!!
goto end
:WARNING
Echo Usage: dbupgrade_CNFMGR [server] [login] [password] [dbname]

:end