IF EXISTS(SELECT 1 FROM sys.objects WHERE name = 'TRADE_SUMMARY' AND type = 'U')
BEGIN
	ALTER TABLE ConfirmMgr.TRADE_SUMMARY
	ADD CPTY_TRADE_ID VARCHAR(50) NULL 
	PRINT 'COLUMN CPTY_TRADE_ID ADDED ON TRADE_SUMMARY'
END
GO

