
package aff.confirm.updateconfirmstatus.mdb.jaxb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import cnf.confirmationsmanager.GetConfirmationTemplatesRequest;
import cnf.confirmationsmanager.GetPermissionKeysRequest;
import cnf.confirmationsmanager.TradeConfirmationStatusChangeRequest;
import cnf.integration.GetConfirmationTemplatesResponse;
import cnf.integration.GetPermissionKeysResponse;
import cnf.integration.TradeConfirmationStatusChangeResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ConfirmationsManager", targetNamespace = "http://cnf/ConfirmationsManager")
@XmlSeeAlso({
    cnf.integration.ObjectFactory.class,
    cnf.confirmationsmanager.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class
})
public interface ConfirmationsManager {


    /**
     * 
     * @param getPermissionKeysRequest
     * @return
     *     returns cnf.integration.GetPermissionKeysResponse
     */
    @WebMethod(action = "http://cnf/ConfirmationsManager/ConfirmationsManager/getPermissionKeys")
    @WebResult(name = "getPermissionKeysResult", targetNamespace = "http://cnf/ConfirmationsManager")
    @RequestWrapper(localName = "getPermissionKeys", targetNamespace = "http://cnf/ConfirmationsManager", className = "cnf.confirmationsmanager.GetPermissionKeys")
    @ResponseWrapper(localName = "getPermissionKeysResponse", targetNamespace = "http://cnf/ConfirmationsManager", className = "cnf.confirmationsmanager.GetPermissionKeysResponse")
    public GetPermissionKeysResponse getPermissionKeys(
        @WebParam(name = "getPermissionKeysRequest", targetNamespace = "http://cnf/ConfirmationsManager")
        GetPermissionKeysRequest getPermissionKeysRequest);

    /**
     * 
     * @param getConfirmationTemplatesRequest
     * @return
     *     returns cnf.integration.GetConfirmationTemplatesResponse
     */
    @WebMethod(action = "http://cnf/ConfirmationsManager/ConfirmationsManager/getConfirmationTemplates")
    @WebResult(name = "getConfirmationTemplatesResult", targetNamespace = "http://cnf/ConfirmationsManager")
    @RequestWrapper(localName = "getConfirmationTemplates", targetNamespace = "http://cnf/ConfirmationsManager", className = "cnf.confirmationsmanager.GetConfirmationTemplates")
    @ResponseWrapper(localName = "getConfirmationTemplatesResponse", targetNamespace = "http://cnf/ConfirmationsManager", className = "cnf.confirmationsmanager.GetConfirmationTemplatesResponse")
    public GetConfirmationTemplatesResponse getConfirmationTemplates(
        @WebParam(name = "getConfirmationTemplatesRequest", targetNamespace = "http://cnf/ConfirmationsManager")
        GetConfirmationTemplatesRequest getConfirmationTemplatesRequest);

    /**
     * 
     * @param tradeConfirmationStatusChangeRequest
     * @return
     *     returns cnf.integration.TradeConfirmationStatusChangeResponse
     */
    @WebMethod(action = "http://cnf/ConfirmationsManager/ConfirmationsManager/tradeConfirmationStatusChange")
    @WebResult(name = "tradeConfirmationStatusChangeResult", targetNamespace = "http://cnf/ConfirmationsManager")
    @RequestWrapper(localName = "tradeConfirmationStatusChange", targetNamespace = "http://cnf/ConfirmationsManager", className = "cnf.confirmationsmanager.TradeConfirmationStatusChange")
    @ResponseWrapper(localName = "tradeConfirmationStatusChangeResponse", targetNamespace = "http://cnf/ConfirmationsManager", className = "cnf.confirmationsmanager.TradeConfirmationStatusChangeResponse")
    public TradeConfirmationStatusChangeResponse tradeConfirmationStatusChange(
        @WebParam(name = "tradeConfirmationStatusChangeRequest", targetNamespace = "http://cnf/ConfirmationsManager")
        TradeConfirmationStatusChangeRequest tradeConfirmationStatusChangeRequest);

}
