ALTER TABLE ConfirmMgr.RQMT 
ADD EXT_WORKFLOW_NAME VARCHAR(50) NULL
GO
PRINT 'COLUMN EXT_WORKFLOW_NAME ADDED ON RQMT TABLE'
GO

CREATE UNIQUE INDEX IDX_RQMT_UQ_1
ON ConfirmMgr.RQMT
(
	EXT_WORKFLOW_NAME ASC
)
WHERE EXT_WORKFLOW_NAME IS NOT NULL;
GO
PRINT 'UNIQUE INDEX IDX_RQMT_UQ_1 ADDED ON RQMT TABLE'
GO

update ConfirmMgr.RQMT set EXT_WORKFLOW_NAME ='OURPAPER' where code='XQCSP'
GO
update ConfirmMgr.RQMT set EXT_WORKFLOW_NAME ='CPTYPAPER' where code='XQCCP'
GO
update ConfirmMgr.RQMT set EXT_WORKFLOW_NAME ='BROKERPAPER' where code='XQBBP'
GO