//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpsTrackingModel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM OPS_TRACKING.V_PC_TRADE_SUMMARY WHERE FINAL_APPROVAL_FLAG = \'N\'")]
        public string SummaryData {
            get {
                return ((string)(this["SummaryData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM OPS_TRACKING.V_PC_TRADE_RQMT WHERE FINAL_APPROVAL_FLAG = \'N\' ORDER " +
            "BY TRANSACTION_SEQ ASC")]
        public string RqmtData {
            get {
                return ((string)(this["RqmtData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from OPS_TRACKING.V_TRADE_RQMT_CONFIRM WHERE FINAL_APPROVAL_FLAG = \'N\'")]
        public string TradeRqmtConfirm {
            get {
                return ((string)(this["TradeRqmtConfirm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from OPS_TRACKING.V_RQMT_STATUS_COLORS")]
        public string RqmtStatusColor {
            get {
                return ((string)(this["RqmtStatusColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from OPS_TRACKING.COLOR_TRANSLATE")]
        public string ColorTranslate {
            get {
                return ((string)(this["ColorTranslate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from OPS_TRACKING.V_RQMT")]
        public string RqmtView {
            get {
                return ((string)(this["RqmtView"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from OPS_TRACKING.V_RQMT_STATUS")]
        public string RqmtStatusView {
            get {
                return ((string)(this["RqmtStatusView"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from OPS_TRACKING.V_TRADE_DATA_CDTY_CODE_LKUP ORDER BY CDTY_CODE ASC")]
        public string BdtaCdtyLkup {
            get {
                return ((string)(this["BdtaCdtyLkup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from OPS_TRACKING.V_TRADE_DATA_CPTY_LKUP ORDER BY SHORT_NAME ASC")]
        public string BdtaCptyLkup {
            get {
                return ((string)(this["BdtaCptyLkup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from OPS_TRACKING.V_INBOUND_DOCS where doc_status_code = \'OPEN\'")]
        public string InboundDocsView {
            get {
                return ((string)(this["InboundDocsView"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select * from OPS_TRACKING.V_ACTIVE_ASSOCIATED_DOCS")]
        public string AssociatedDocs {
            get {
                return ((string)(this["AssociatedDocs"]));
            }
        }
    }
}
