//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InboundFileProcessor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TimerIntervalMinutes {
            get {
                return ((int)(this["TimerIntervalMinutes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("doc,docx,htm,html,pdf,rtf,tif,txt,xls,xlsx")]
        public string ValidFileExt {
            get {
                return ((string)(this["ValidFileExt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugLogEnabled {
            get {
                return ((bool)(this["DebugLogEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Amphora Inc.-DOCIMG_RASPDFR175.lic")]
        public string LeadtoolsLicenseFile {
            get {
                return ((string)(this["LeadtoolsLicenseFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5cxfXs1TnpaXbVXDIdFzk9iRWcBBLjcIoN2W3sVpvDPvoNzYNmOr1zmYg3qhCnFE")]
        public string LeadtoolsDeveloperKey {
            get {
                return ((string)(this["LeadtoolsDeveloperKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=CNF01INFDBS01\\SQLSVR11;Database=cnf_mgr;integrated security=sspi;")]
        public string SqlConnectionIntegratedSecurityString {
            get {
                return ((string)(this["SqlConnectionIntegratedSecurityString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>\\\\cnf01inf01\\CNF01\\InboundDocs</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ScanDirectories {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ScanDirectories"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\homeware\\cnf-InboundFileProcessorService\\InboundFiles\\ConvertedTIFs")]
        public string OutputDirectory {
            get {
                return ((string)(this["OutputDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\homeware\\cnf-InboundFileProcessorService\\InboundFiles\\processed")]
        public string ProcessedDirectory {
            get {
                return ((string)(this["ProcessedDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\cnf01inf01\\CNF01\\InboundDocs-Failed")]
        public string FailedDirectory {
            get {
                return ((string)(this["FailedDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AFF01INFMAIL")]
        public string EmailHost {
            get {
                return ((string)(this["EmailHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int EmailPort {
            get {
                return ((int)(this["EmailPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jvega@amphorainc.com")]
        public string EmailNotifyAddresses {
            get {
                return ((string)(this["EmailNotifyAddresses"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EmailEnabled {
            get {
                return ((bool)(this["EmailEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("amphorainc.com")]
        public string EmailSenderDomain {
            get {
                return ((string)(this["EmailSenderDomain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FailedToConvert")]
        public string FailedSubDirConvert {
            get {
                return ((string)(this["FailedSubDirConvert"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unsupported")]
        public string FailedSubDirUnsupported {
            get {
                return ((string)(this["FailedSubDirUnsupported"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeleteTIFEnabled {
            get {
                return ((bool)(this["DeleteTIFEnabled"]));
            }
        }
    }
}
