IF EXISTS(SELECT 1 FROM sys.tables tbl inner join sys.columns cl ON tbl.object_id = cl.object_id WHERE tbl.name = 'ASSOCIATED_DOCS' AND cl.name = 'FILE_NAME' )
	BEGIN
		ALTER TABLE ConfirmMgr.ASSOCIATED_DOCS
		ALTER COLUMN FILE_NAME VARCHAR(150) NULL;
	END;
ELSE
	BEGIN
		PRINT 'COLUMN OR TABLE NOT EXISTS'
	END;
GO
PRINT 'ALTER TABLE ASSOCIATED_DOCS FINISHED'
GO