package aff.confirm.webservices.tradegateway.opsmgrws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6-redhat-1
 * 2013-08-13T06:57:05.513-04:00
 * Generated source version: 2.4.6-redhat-1
 * 
 */
@WebServiceClient(name = "OpsMgrWSService", 
                  wsdlLocation = "file:/C:/Users/ifrankel/AppDev/JavaProjects/Confirmations/aff/confirm/webservices/tradegateway/AmphoraOpsMgrWS.wsdl",
                  targetNamespace = "http://tc/OpsMgrWS") 
public class OpsMgrWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tc/OpsMgrWS", "OpsMgrWSService");
    public final static QName OpsMgrWSPort = new QName("http://tc/OpsMgrWS", "OpsMgrWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/ifrankel/AppDev/JavaProjects/Confirmations/aff/confirm/webservices/tradegateway/AmphoraOpsMgrWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OpsMgrWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/ifrankel/AppDev/JavaProjects/Confirmations/aff/confirm/webservices/tradegateway/AmphoraOpsMgrWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OpsMgrWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OpsMgrWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpsMgrWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OpsMgrWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OpsMgrWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OpsMgrWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OpsMgrWS
     */
    @WebEndpoint(name = "OpsMgrWSPort")
    public OpsMgrWS getOpsMgrWSPort() {
        return super.getPort(OpsMgrWSPort, OpsMgrWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpsMgrWS
     */
    @WebEndpoint(name = "OpsMgrWSPort")
    public OpsMgrWS getOpsMgrWSPort(WebServiceFeature... features) {
        return super.getPort(OpsMgrWSPort, OpsMgrWS.class, features);
    }

}
