package aff.confirm.webservices.tradegateway.opsmgrws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.naming.spi.ObjectFactory;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6-redhat-1
 * 2013-08-13T06:57:05.419-04:00
 * Generated source version: 2.4.6-redhat-1
 * 
 */
@WebService(targetNamespace = "http://tc/OpsMgrWS", name = "OpsMgrWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OpsMgrWS {

    @WebResult(name = "getTradeAlertOpsTrackXMLResponse", targetNamespace = "http://tc/OpsMgrWS", partName = "getTradeAlertOpsTrackXMLResponse")
    @WebMethod
    public java.lang.String getTradeAlertOpsTrackXML(
        @WebParam(partName = "ticketId", name = "ticketId", targetNamespace = "http://tc/OpsMgrWS")
        int ticketId
    );

    @WebResult(name = "getContractFeedXMLResponse", targetNamespace = "http://tc/OpsMgrWS", partName = "getContractFeedXMLResponse")
    @WebMethod
    public java.lang.String getContractFeedXML(
        @WebParam(partName = "tradeId", name = "tradeId", targetNamespace = "http://tc/OpsMgrWS")
        int tradeId
    );

    @WebResult(name = "getTradeAlertMessageXMLResponse", targetNamespace = "http://tc/OpsMgrWS", partName = "getTradeAlertMessageXMLResponse")
    @WebMethod
    public java.lang.String getTradeAlertMessageXML(
        @WebParam(partName = "ticket", name = "ticket", targetNamespace = "http://tc/OpsMgrWS")
        int ticket
    );
}
