IF OBJECT_ID('ConfirmMgr.V_DOCS_TO_VAULT','V') IS NULL
EXEC ('CREATE VIEW ConfirmMgr.V_DOCS_TO_VAULT AS SELECT 1')
GO

ALTER VIEW ConfirmMgr.V_DOCS_TO_VAULT 
AS

SELECT 
VD.ID VAULTED_DOCS_ID,
VD.TRADE_RQMT_CONFIRM_ID VAULTED_DOCS_TRADE_RQMT_CONFIRM_ID, 
VD.ASSOCIATED_DOCS_ID VAULTED_DOCS_ASSOCIATED_DOCS_ID,
VD.SENT_FLAG VAULTED_DOCS_SENT_FLAG,
VD.METADATA VAULTED_DOCS_METADATA,
VD.REQUEST_TIMESTAMP VAULTED_DOCS_REQUEST_TIMESTAMP, 
VDB.ID VAULTED_DOCS_BLOB_ID, 
VDB.IMAGE_FILE_EXT VAULTED_DOCS_BLOB_IMAGE_FILE_EXT,
RDC.RQMT_CODE RQMT_DOC_TYPE_RQMT_CODE, 
RDC.SENT_FLAG RQMT_DOC_TYPE_SENT_FLAG,
RDC.DOC_TYPE_CODE RQMT_DOC_TYPE_DOC_TYPE_CODE,
T.TRD_SYS_CODE,
T.TRD_SYS_TICKET
FROM 
ConfirmMgr.VAULTED_DOCS VD
JOIN ConfirmMgr.VAULTED_DOCS_BLOB VDB
       ON VD.ID = VDB.VAULTED_DOCS_ID
JOIN ConfirmMgr.ASSOCIATED_DOCS AD
       ON VD.ASSOCIATED_DOCS_ID = AD.ID
JOIN ConfirmMgr.RQMT_DOC_TYPE RDC
       ON AD.DOC_TYPE_CODE = RDC.RQMT_CODE
       AND VD.SENT_FLAG = RDC.SENT_FLAG
JOIN ConfirmMgr.TRADE_RQMT TR
       ON AD.TRADE_RQMT_ID = TR.ID
JOIN ConfirmMgr.TRADE T
       ON TR.TRADE_ID = T.ID
WHERE PROCESSED_FLAG = 'N'

UNION ALL

SELECT 
VD.ID VAULTED_DOCS_ID,
VD.TRADE_RQMT_CONFIRM_ID VAULTED_DOCS_TRADE_RQMT_CONFIRM_ID, 
VD.ASSOCIATED_DOCS_ID VAULTED_DOCS_ASSOCIATED_DOCS_ID,
VD.SENT_FLAG VAULTED_DOCS_SENT_FLAG,
VD.METADATA VAULTED_DOCS_METADATA,
VD.REQUEST_TIMESTAMP VAULTED_DOCS_REQUEST_TIMESTAMP, 
VDB.ID VAULTED_DOCS_BLOB_ID, 
VDB.IMAGE_FILE_EXT VAULTED_DOCS_BLOB_IMAGE_FILE_EXT,
RDC.RQMT_CODE RQMT_DOC_TYPE_RQMT_CODE, 
RDC.SENT_FLAG RQMT_DOC_TYPE_SENT_FLAG,
RDC.DOC_TYPE_CODE RQMT_DOC_TYPE_DOC_TYPE_CODE,
T.TRD_SYS_CODE,
T.TRD_SYS_TICKET
FROM 
ConfirmMgr.VAULTED_DOCS VD
JOIN ConfirmMgr.VAULTED_DOCS_BLOB VDB
       ON VD.ID = VDB.VAULTED_DOCS_ID
JOIN ConfirmMgr.ASSOCIATED_DOCS AD
       ON VD.ASSOCIATED_DOCS_ID = AD.ID
JOIN ConfirmMgr.TRADE_RQMT TR
       ON AD.TRADE_RQMT_ID = TR.ID
JOIN ConfirmMgr.RQMT_DOC_TYPE RDC
       ON TR.RQMT = RDC.RQMT_CODE
       AND VD.SENT_FLAG = RDC.SENT_FLAG
JOIN ConfirmMgr.TRADE T
       ON TR.TRADE_ID = T.ID
WHERE PROCESSED_FLAG = 'N'
GO
