IF OBJECT_ID('ConfirmMgr.SEQ_XMIT_REQUEST','SO') IS NOT NULL
EXEC ('DROP SEQUENCE ConfirmMgr.SEQ_XMIT_REQUEST')
GO
CREATE SEQUENCE ConfirmMgr.SEQ_XMIT_REQUEST
 AS [int]
 START WITH 1
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 99999999
 NO CACHE 
GO
GRANT UPDATE ON ConfirmMgr.SEQ_XMIT_REQUEST TO stanford_developers
GO
PRINT 'SEQ_XMIT_REQUEST CREATED SUCCESSFULLY!!!!'



