IF EXISTS(SELECT 1 FROM sys.objects WHERE name = 'TR_XMIT_REQUEST_BER_IU')
DROP TRIGGER ConfirmMgr.TR_XMIT_REQUEST_BER_IU
GO
CREATE TRIGGER ConfirmMgr.TR_XMIT_REQUEST_BER_IU
ON ConfirmMgr.XMIT_REQUEST
INSTEAD OF INSERT, UPDATE
AS
/******************************************************************************
*
* AUTHOR:		JAVIER MONTERO - 11/09/2015
* DB:			SQL SERVER 2012 OR HIGHER
* VERSION:		1.0
* DESCRIPTION:  TRIGGER FOR INSERT AND UPDATE ACTIONS ON TABLE XMIT_REQUEST
				THIS TRIGGER CHECKS IF THE FIELDS TRADE_RQMT_CONFIRM_ID OR
				ASSOCIATED_DOCS_ID IS NULL, BECAUSE THEM CANNOT BE NULL OR
				NOT NULL IN SAME TIME
* DEPENCIES:    TABLE XMIT_REQUEST IS REQUIERED
*
*******************************************************************************/
BEGIN
SET NOCOUNT ON
declare 
@trrqmtid	int,
@asocdocid	int

	SELECT @trrqmtid = TRADE_RQMT_CONFIRM_ID, @asocdocid = ASSOCIATED_DOCS_ID FROM inserted

	IF @trrqmtid IS NULL AND @asocdocid IS NOT NULL
		BEGIN
			INSERT ConfirmMgr.XMIT_REQUEST
			(ID, TRADE_RQMT_CONFIRM_ID, ASSOCIATED_DOCS_ID, XMIT_METHOD_IND, XMIT_DEST,SENT_BY_USER)
			SELECT 
			i.ID,
			i.TRADE_RQMT_CONFIRM_ID,
			i.ASSOCIATED_DOCS_ID,
			i.XMIT_METHOD_IND,
			i.XMIT_DEST,
			i.SENT_BY_USER
		FROM inserted i
			RETURN
		END
	ELSE IF @trrqmtid IS NOT NULL AND @asocdocid IS NULL
	BEGIN 
		INSERT ConfirmMgr.XMIT_REQUEST
		(ID, TRADE_RQMT_CONFIRM_ID, ASSOCIATED_DOCS_ID, XMIT_METHOD_IND, XMIT_DEST,SENT_BY_USER)
		SELECT 
		i.ID,
		i.TRADE_RQMT_CONFIRM_ID,
		i.ASSOCIATED_DOCS_ID,
		i.XMIT_METHOD_IND,
		i.XMIT_DEST,
		i.SENT_BY_USER
		FROM inserted i
		RETURN
	END
	ELSE IF  @trrqmtid IS NOT NULL AND @asocdocid IS NOT NULL
	BEGIN
		RAISERROR('PLEASE ONLY PASS TRADE_RQMT_CONFIRM_ID OR AN ASSOCIATED_DOCS_ID.',1,1) WITH NOWAIT
		ROLLBACK
		RETURN
	END
	ELSE IF  @trrqmtid IS NULL AND @asocdocid IS NULL
	BEGIN
		RAISERROR('PLEASE PASS EITHER A TRADE_RQMT_CONFIRM_ID OR AN ASSOCIATED_DOCS_ID.',1,1) WITH NOWAIT
		ROLLBACK
		RETURN
	END
END
GO
PRINT 'TRIGGER ConfirmMgr.TR_XMIT_REQUEST_BER_I CREATED SUCCESSFULLY'
GO