DECLARE
@errormsg		nvarchar(max)
BEGIN
	BEGIN TRY 
		IF NOT EXISTS(SELECT 1 FROM ConfirmMgr.RQMT_STATUS WHERE RQMT_CODE = 'XQCSP' AND STATUS_CODE = 'DISP_CPTY')
			BEGIN 
				INSERT INTO ConfirmMgr.RQMT_STATUS VALUES('XQCSP','DISP_CPTY','Y',12,'N','Y','RED')
			END
		ELSE
			BEGIN
				PRINT 'CODE EXISTS ON RQMT_STATUS TABLE';
			END
	END TRY
	BEGIN CATCH
		SELECT @errormsg = 'ERROR: ' + ERROR_MESSAGE() + ' ERROR LINE: ' + cast(ERROR_LINE() as int);
		THROW 51000, @errormsg, 1
	END CATCH
END
GO
PRINT 'INSERT STATUS CODE ON RQMT_STATUS TABLE FINISHED'
GO
