//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using DevExpress.XtraBars;
using DevExpress.XtraBars.Ribbon;
using DevExpress.XtraEditors;
using NSRiskMgrCtrls;
using System.Xml;
using System.Collections.Generic;
using System.IO;
namespace NSRiskManager {
 

    public partial class RiskManagerForm : /* RibbonForm */ XtraForm {
        #region fields
        /// <summary>
        /// Required designer variable.
        /// </summary>
        IContainer components = null;
        #endregion

        BackgroundWorker dataLoadBackgroundWorker;


        #region Windows Form Designer generated code
        /// <summary>Required method for Designer support</summary>
        void InitializeComponent() {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(RiskManagerForm));
            this.dataLoadBackgroundWorker = new System.ComponentModel.BackgroundWorker();
            this.splitContainerControl1 = new DevExpress.XtraEditors.SplitContainerControl();
            this.treeList1 = new DevExpress.XtraTreeList.TreeList();
            this.cmsPortfolios = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.ctxNewPortfolio = new System.Windows.Forms.ToolStripMenuItem();
            this.ctxNewAsCopyOf = new System.Windows.Forms.ToolStripMenuItem();
            this.ctxUpdatePortfolio = new System.Windows.Forms.ToolStripMenuItem();
            this.ctxDeletePortfolio = new System.Windows.Forms.ToolStripMenuItem();
            this.inspectablePivotGrid1 = new NSRiskMgrCtrls.InspectablePivotGrid();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerControl1)).BeginInit();
            this.splitContainerControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.treeList1)).BeginInit();
            this.cmsPortfolios.SuspendLayout();
            this.SuspendLayout();
            // 
            // splitContainerControl1
            // 
            this.splitContainerControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainerControl1.Location = new System.Drawing.Point(0, 0);
            this.splitContainerControl1.Name = "splitContainerControl1";
            this.splitContainerControl1.Panel1.Controls.Add(this.treeList1);
            this.splitContainerControl1.Panel1.Text = "Panel1";
            this.splitContainerControl1.Panel2.Controls.Add(this.inspectablePivotGrid1);
            this.splitContainerControl1.Panel2.Text = "Panel2";
            this.splitContainerControl1.Size = new System.Drawing.Size(710, 501);
            this.splitContainerControl1.TabIndex = 2;
            this.splitContainerControl1.Text = "splitContainerControl1";
            // 
            // treeList1
            // 
            this.treeList1.ContextMenuStrip = this.cmsPortfolios;
            this.treeList1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treeList1.Location = new System.Drawing.Point(0, 0);
            this.treeList1.Name = "treeList1";
            this.treeList1.Size = new System.Drawing.Size(100, 501);
            this.treeList1.TabIndex = 0;
            this.treeList1.GetSelectImage += new DevExpress.XtraTreeList.GetSelectImageEventHandler(this.treeList1_GetSelectImage);
            this.treeList1.BeforeExpand += new DevExpress.XtraTreeList.BeforeExpandEventHandler(this.treeList_BeforeExpand);
            this.treeList1.FocusedNodeChanged += new DevExpress.XtraTreeList.FocusedNodeChangedEventHandler(this.treeList1_FocusedNodeChanged);
            this.treeList1.CalcNodeDragImageIndex += new DevExpress.XtraTreeList.CalcNodeDragImageIndexEventHandler(this.treeList1_CalcNodeDragImageIndex);
            this.treeList1.DragDrop += new System.Windows.Forms.DragEventHandler(this.treeList1_DragDrop);
            this.treeList1.DragOver += new System.Windows.Forms.DragEventHandler(this.treeList1_DragOver);
            this.treeList1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.treelist1_MouseDown);
            // 
            // cmsPortfolios
            // 
            this.cmsPortfolios.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.cmsPortfolios.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.ctxNewPortfolio,
            this.ctxNewAsCopyOf,
            this.ctxUpdatePortfolio,
            this.ctxDeletePortfolio});
            this.cmsPortfolios.Name = "contextMenuStrip1";
            this.cmsPortfolios.Size = new System.Drawing.Size(213, 92);
            this.cmsPortfolios.Opening += new System.ComponentModel.CancelEventHandler(this.cmsPortfolios_Opening);
            // 
            // ctxNewPortfolio
            // 
            this.ctxNewPortfolio.Name = "ctxNewPortfolio";
            this.ctxNewPortfolio.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.N)));
            this.ctxNewPortfolio.Size = new System.Drawing.Size(212, 22);
            this.ctxNewPortfolio.Text = "New...";
            this.ctxNewPortfolio.Click += new System.EventHandler(this.ctxNewPortfolio_Click);
            // 
            // ctxNewAsCopyOf
            // 
            this.ctxNewAsCopyOf.Name = "ctxNewAsCopyOf";
            this.ctxNewAsCopyOf.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.C)));
            this.ctxNewAsCopyOf.Size = new System.Drawing.Size(212, 22);
            this.ctxNewAsCopyOf.Text = "New as &copy of...";
            this.ctxNewAsCopyOf.Click += new System.EventHandler(this.ctxNewAsCopyOf_Click);
            // 
            // ctxUpdatePortfolio
            // 
            this.ctxUpdatePortfolio.Name = "ctxUpdatePortfolio";
            this.ctxUpdatePortfolio.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.U)));
            this.ctxUpdatePortfolio.Size = new System.Drawing.Size(212, 22);
            this.ctxUpdatePortfolio.Text = "&Update portfolio...";
            this.ctxUpdatePortfolio.Click += new System.EventHandler(this.ctxUpdatePortfolio_Click);
            // 
            // ctxDeletePortfolio
            // 
            this.ctxDeletePortfolio.Name = "ctxDeletePortfolio";
            this.ctxDeletePortfolio.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D)));
            this.ctxDeletePortfolio.Size = new System.Drawing.Size(212, 22);
            this.ctxDeletePortfolio.Text = "&Delete portfolio...";
            this.ctxDeletePortfolio.Click += new System.EventHandler(this.ctxDeletePortfolio_Click);
            // 
            // inspectablePivotGrid1
            // 
            this.inspectablePivotGrid1.AllowDrop = true;
            this.inspectablePivotGrid1.dataProvider = null;
            this.inspectablePivotGrid1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.inspectablePivotGrid1.Location = new System.Drawing.Point(0, 0);
            this.inspectablePivotGrid1.lowerSplitPosition = 280;
            this.inspectablePivotGrid1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.inspectablePivotGrid1.Name = "inspectablePivotGrid1";
            this.inspectablePivotGrid1.NumPositionsOnScreen = 0;
            this.inspectablePivotGrid1.NumRealPortfoliosOnScreen = 0;
            this.inspectablePivotGrid1.pivotDataType = null;
            this.inspectablePivotGrid1.pnlSplitPosition = 318;
            this.inspectablePivotGrid1.Size = new System.Drawing.Size(605, 501);
            this.inspectablePivotGrid1.TabIndex = 0;
            this.inspectablePivotGrid1.uomRequester = null;
            // 
            // RiskManagerForm
            // 
            this.AllowDrop = true;
            this.ClientSize = new System.Drawing.Size(710, 501);
            this.Controls.Add(this.splitContainerControl1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "RiskManagerForm";
            this.Load += new System.EventHandler(this.formLoad);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerControl1)).EndInit();
            this.splitContainerControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.treeList1)).EndInit();
            this.cmsPortfolios.ResumeLayout(false);
            this.ResumeLayout(false);

        }
        XmlDocument windowsPositsionsXml =  new XmlDocument();
        XmlElement riskWindowElements;
        public void CaptureApplicaionPositions(object riskMgrForm)
        {
            
            if (!IsInitializing && riskMgrForm is RiskManagerForm && riskManagerFormLoaded)
            {
                (riskMgrForm as RiskManagerForm).inspectablePivotGrid1.scPnlGrids.SizeChanged -= new EventHandler(scPnlGrids_SizeChanged);
                (riskMgrForm as RiskManagerForm).inspectablePivotGrid1.scPnlGrids.SizeChanged += new EventHandler(scPnlGrids_SizeChanged);
                    
                if( RiskManagerWindowManager.windows != null)
                {
                    List<RiskManagerWindowState> listOfRMWindows = new List<RiskManagerWindowState>();
                    foreach (RiskManagerForm rmform in RiskManagerWindowManager.windows.Values)
                    {
                        IWindowLayoutProvider tempIwlp = rmform as IWindowLayoutProvider;
                        RiskManagerWindowState rmWState = new RiskManagerWindowState();
                        rmWState.win_id = rmform.windowDef.windowId;
                        rmWState.lower_split_pos = tempIwlp.lowerSplitPosition;
                        rmWState.pnl_split_pos = tempIwlp.pnlSplitPosition;
                        rmWState.port_split_pos = tempIwlp.portSplitPosition;
                        string tmp = this.DesktopBounds.ToString();
                        //if (string.Compare(tmp, tempIwlp.windowFrame.ToString()) != 0)
                            rmWState.window_frame = tmp;
                       // else
                       //     rmWState.window_frame = windowDef.windowFrame;
                        rmWState.display_Resolution = System.Windows.Forms.Screen.PrimaryScreen.Bounds.Width.ToString() +
                                                      "*" + System.Windows.Forms.Screen.PrimaryScreen.Bounds.Height.ToString();
                        listOfRMWindows.Add(rmWState);
                    }
                    if (listOfRMWindows != null && listOfRMWindows.Count > 0)//Writing to local store xml
                    {
                        try
                        {
                            if (!Directory.Exists(localStorePath))
                                Directory.CreateDirectory(localStorePath);

                            using (var wfile = new System.IO.StreamWriter(localStorePath + "ListOfRiskManagerWindowsXml.xml"))
                            {
                                var writer = new System.Xml.Serialization.XmlSerializer(typeof(List<RiskManagerWindowState>));
                                writer.Serialize(wfile, listOfRMWindows);
                                wfile.Close();
                            }
                        }
                        catch (Exception ex)
                        {
                        }
                    }
                }

            }
        }

        void scPivotAndLower_SizeChanged(object sender, EventArgs e)
        {
            CaptureApplicaionPositions(this);
        }

        void xtraTabControl1_SizeChanged(object sender, EventArgs e)
        {
            CaptureApplicaionPositions(this);
        }


        void scPnlGrids_SizeChanged(object sender, EventArgs e)
        {
            CaptureApplicaionPositions(this);
        }

        void RiskManagerForm_LocationChanged(object sender, EventArgs e)
        {
            CaptureApplicaionPositions(sender);
        }

        void RiskManagerForm_SizeChanged(object sender, EventArgs e)
        {
            CaptureApplicaionPositions(sender);
        }
        #endregion

        bool disposed;
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing) {
            if (disposing) {
                disposed = true;
        
                doShutdown();                
                if ((components != null)) {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        private SplitContainerControl splitContainerControl1;
        private DevExpress.XtraTreeList.TreeList treeList1;
        private System.Windows.Forms.ContextMenuStrip cmsPortfolios;
        private InspectablePivotGrid inspectablePivotGrid1;
        private System.Windows.Forms.ToolStripMenuItem ctxNewPortfolio;
        private System.Windows.Forms.ToolStripMenuItem ctxNewAsCopyOf;
        private System.Windows.Forms.ToolStripMenuItem ctxUpdatePortfolio;
        private System.Windows.Forms.ToolStripMenuItem ctxDeletePortfolio;
        
    }
}