//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.XtraBars;
using DevExpress.XtraBars.Ribbon;
using DevExpress.XtraEditors;
using System;
using System.ComponentModel;
using System.Diagnostics;


namespace NSDriver {
    
    public partial class driverForm : RibbonForm {
        #region fields
        /// <summary>
        /// Required designer variable.
        /// </summary>
        IContainer components = null;
        RibbonControl ribbonControl;
        RibbonPage ribbonPage;
        RibbonPageGroup ribbonPageGroup;
        BarButtonItem bbExit;
        BarButtonItem bbAbout;
        RibbonStatusBar ribbonStatusBar;
        #endregion
        #region Windows Form Designer generated code
        /// <summary>Required method for Designer support</summary>
        void InitializeComponent() {
            this.ribbonControl = new DevExpress.XtraBars.Ribbon.RibbonControl();
            this.bbExit = new DevExpress.XtraBars.BarButtonItem();
            this.bbAbout = new DevExpress.XtraBars.BarButtonItem();
            this.ribbonPage = new DevExpress.XtraBars.Ribbon.RibbonPage();
            this.ribbonPageGroup = new DevExpress.XtraBars.Ribbon.RibbonPageGroup();
            this.ribbonStatusBar = new DevExpress.XtraBars.Ribbon.RibbonStatusBar();
            this.amphoraFieldSelector1 = new NSFS.AmphoraFieldSelector();
            ((System.ComponentModel.ISupportInitialize)(this.ribbonControl)).BeginInit();
            this.SuspendLayout();
            // 
            // ribbonControl
            // 
            this.ribbonControl.ExpandCollapseItem.Id = 0;
            this.ribbonControl.Items.AddRange(new DevExpress.XtraBars.BarItem[] {
            this.ribbonControl.ExpandCollapseItem,
            this.bbExit,
            this.bbAbout});
            this.ribbonControl.Location = new System.Drawing.Point(0, 0);
            this.ribbonControl.MaxItemId = 3;
            this.ribbonControl.Name = "ribbonControl";
            this.ribbonControl.PageHeaderItemLinks.Add(this.bbAbout);
            this.ribbonControl.Pages.AddRange(new DevExpress.XtraBars.Ribbon.RibbonPage[] {
            this.ribbonPage});
            this.ribbonControl.PopupShowMode = DevExpress.XtraBars.PopupShowMode.Classic;
            this.ribbonControl.Size = new System.Drawing.Size(570, 155);
            this.ribbonControl.StatusBar = this.ribbonStatusBar;
            // 
            // bbExit
            // 
            this.bbExit.Caption = "Exit";
            this.bbExit.Id = 1;
            this.bbExit.Name = "bbExit";
            this.bbExit.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.exitApp);
            // 
            // bbAbout
            // 
            this.bbAbout.Id = 2;
            this.bbAbout.Name = "bbAbout";
            this.bbAbout.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.showAbout);
            // 
            // ribbonPage
            // 
            this.ribbonPage.Groups.AddRange(new DevExpress.XtraBars.Ribbon.RibbonPageGroup[] {
            this.ribbonPageGroup});
            this.ribbonPage.Name = "ribbonPage";
            this.ribbonPage.Text = "File";
            // 
            // ribbonPageGroup
            // 
            this.ribbonPageGroup.ItemLinks.Add(this.bbExit);
            this.ribbonPageGroup.Name = "ribbonPageGroup";
            this.ribbonPageGroup.Text = "File";
            // 
            // ribbonStatusBar
            // 
            this.ribbonStatusBar.Location = new System.Drawing.Point(0, 566);
            this.ribbonStatusBar.Name = "ribbonStatusBar";
            this.ribbonStatusBar.Ribbon = this.ribbonControl;
            this.ribbonStatusBar.Size = new System.Drawing.Size(570, 31);
            // 
            // amphoraFieldSelector1
            // 
            this.amphoraFieldSelector1.aColor = System.Drawing.Color.Red;
            this.amphoraFieldSelector1.AutoScroll = true;
            this.amphoraFieldSelector1.Dock = System.Windows.Forms.DockStyle.Left;
            this.amphoraFieldSelector1.Location = new System.Drawing.Point(0, 155);
            this.amphoraFieldSelector1.Name = "amphoraFieldSelector1";
            this.amphoraFieldSelector1.Size = new System.Drawing.Size(107, 411);
            this.amphoraFieldSelector1.TabIndex = 8;
            // 
            // driverForm
            // 
            this.ClientSize = new System.Drawing.Size(570, 597);
            this.Controls.Add(this.amphoraFieldSelector1);
            this.Controls.Add(this.ribbonStatusBar);
            this.Controls.Add(this.ribbonControl);
            this.Name = "driverForm";
            this.Ribbon = this.ribbonControl;
            this.RibbonVisibility = DevExpress.XtraBars.Ribbon.RibbonVisibility.Visible;
            this.StatusBar = this.ribbonStatusBar;
            this.Load += new System.EventHandler(this.formLoad);
            ((System.ComponentModel.ISupportInitialize)(this.ribbonControl)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        #endregion
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing) {
            if (disposing) {
                if ((components != null)) {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        private NSFS.AmphoraFieldSelector amphoraFieldSelector1;
    }
}
