IF OBJECT_ID('ConfirmMgr.TMP_MERCURIA_TRADE_DATA','U') IS NOT NULL
EXEC('DROP TABLE ConfirmMgr.TMP_MERCURIA_TRADE_DATA')
GO
CREATE TABLE ConfirmMgr.TMP_MERCURIA_TRADE_DATA
(
TRADE	int null,
DEL_START_DATE	date null,
DEL_END_DATE	date null
)
GO
PRINT 'TABLE TMP_MERCURIA_TRADE_DATA CREATED'
GO

