IF EXISTS(SELECT 1 FROM sys.tables tbl inner join sys.columns cl ON tbl.object_id = cl.object_id WHERE tbl.name = 'INBOUND_DOCS' AND cl.name = 'FILE_NAME' )
	BEGIN
		ALTER TABLE ConfirmMgr.INBOUND_DOCS
		ALTER COLUMN FILE_NAME VARCHAR(150) NOT NULL;
	END;
ELSE
	BEGIN
		PRINT 'COLUMN OR TABLE NOT EXISTS'
	END;
GO
PRINT 'ALTER TABLE INBOUND_DOCS IS FINISHED'
GO