IF OBJECT_ID('ConfirmMgr.DATABASE_INFO','U') IS NOT NULL
EXEC ('DROP TABLE ConfirmMgr.DATABASE_INFO')
GO
CREATE TABLE ConfirmMgr.DATABASE_INFO
(
	owner_code			VARCHAR(15) NOT NULL DEFAULT('CONFIRMGR'),
	major_revnum		VARCHAR(20)	NULL,
	minor_revnum		VARCHAR(20) NULL,
	last_touch_date		DATETIME2	NOT NULL DEFAULT (GETDATE()),
	data_source			VARCHAR(50) NULL,
	usage				VARCHAR(30) NULL,
	script_reference	VARCHAR(80) NULL,
	note				VARCHAR(255) NULL
);

ALTER TABLE ConfirmMgr.DATABASE_INFO
ADD CONSTRAINT PK_database_info PRIMARY KEY (last_touch_date);
GO

PRINT 'TABLE DATABASE_INFO CREATED WITH SUCCESS'
GO